const AUDIO_FILES=AUDIO_DATA;
class FightAudio{
 constructor(){this.enabled=true;this.effectsVolume=.85;this.musicVolume=.8;this.musicScene=1;this.running=false;this.buffers={};this.voices=new Set();this.offset=0;this.lastVoice={};this.duckUntil=0;this.errors=[];this.resumeClips=[]}
 async prepare(){if(this.promise)return this.promise;this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.ctx.resume();this.master=this.ctx.createGain();this.master.gain.value=this.enabled?1:0;this.limiter=this.ctx.createDynamicsCompressor();this.limiter.threshold.value=-9;this.limiter.knee.value=8;this.limiter.ratio.value=6;this.limiter.attack.value=.003;this.limiter.release.value=.12;this.limiter.connect(this.master);this.headroom=this.ctx.createGain();this.headroom.gain.value=.65;this.master.connect(this.headroom);this.headroom.connect(this.ctx.destination);this.fx=this.ctx.createGain();this.fx.gain.value=this.effectsVolume;this.fx.connect(this.limiter);this.musicGain=this.ctx.createGain();this.musicGain.gain.value=this.musicVolume*this.musicScene;this.musicGain.connect(this.master);
 this.promise=Promise.all(Object.entries(AUDIO_FILES).map(async([name,encoded])=>{try{const raw=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));let b=await this.ctx.decodeAudioData(raw.buffer);if(name!=='music'){let peak=0,first=b.length,last=0;for(let ch=0;ch<b.numberOfChannels;ch++){const a=b.getChannelData(ch);for(let i=0;i<a.length;i++)peak=Math.max(peak,Math.abs(a[i]))}const threshold=Math.max(.001,peak*.012);for(let ch=0;ch<b.numberOfChannels;ch++){const a=b.getChannelData(ch);for(let i=0;i<a.length;i++)if(Math.abs(a[i])>threshold){first=Math.min(first,i);last=Math.max(last,i)}}first=Math.max(0,first-Math.round(b.sampleRate*.004));last=Math.min(b.length,last+Math.round(b.sampleRate*.08));if(last>first){const clean=this.ctx.createBuffer(b.numberOfChannels,last-first,b.sampleRate),gain=Math.min(3,.85/(peak||1));for(let ch=0;ch<b.numberOfChannels;ch++){const a=b.getChannelData(ch),out=clean.getChannelData(ch);for(let i=0;i<out.length;i++)out[i]=a[first+i]*gain}b=clean}}this.buffers[name]=b}catch(e){this.errors.push(name)}}));return this.promise}
 start(){if(!this.ctx)return;this.ctx.resume();this.running=true;this.fx.gain.value=this.effectsVolume;this.musicGain.gain.cancelScheduledValues(this.ctx.currentTime);this.musicGain.gain.value=this.musicVolume*this.musicScene;if(this.musicSource||!this.buffers.music)return;const source=this.ctx.createBufferSource();source.buffer=this.buffers.music;source.loop=true;source.connect(this.musicGain);source.start(0,this.offset%source.buffer.duration);this.musicStart=this.ctx.currentTime;this.musicSource=source;const pending=this.resumeClips.splice(0);for(const clip of pending)this.play(clip.name,clip)}
 pause(reset=false){this.resumeClips=[];for(const source of this.voices){const clip=source.clip;if(clip&&!reset){const offset=clip.offset+Math.max(0,this.ctx.currentTime-clip.started);if(offset<source.buffer.duration)this.resumeClips.push({...clip,offset,delay:Math.max(0,clip.started-this.ctx.currentTime)})}}this.running=false;if(this.musicSource){this.offset=(this.offset+this.ctx.currentTime-this.musicStart)%this.buffers.music.duration;this.musicSource.stop();this.musicSource.disconnect();this.musicSource=null}for(const s of this.voices){try{s.stop()}catch{}}this.voices.clear();if(reset){this.offset=0;this.lastVoice={}}}
 mute(value){this.enabled=!value;if(this.master)this.master.gain.setTargetAtTime(this.enabled?1:0,this.ctx.currentTime,.015)}
 volumes(fx,music){this.effectsVolume=fx;this.musicVolume=music;if(this.fx)this.fx.gain.setTargetAtTime(fx,this.ctx.currentTime,.03);if(this.musicGain){this.musicGain.gain.cancelScheduledValues(this.ctx.currentTime);this.musicGain.gain.setTargetAtTime(music*this.musicScene,this.ctx.currentTime,.05)}}
 introMix(value){this.musicScene=value;if(this.musicGain){const t=this.ctx.currentTime;this.musicGain.gain.cancelScheduledValues(t);this.musicGain.gain.setTargetAtTime(this.musicVolume*value,t,.22)}}
 stopCinematic(){this.resumeClips=[];for(const s of [...this.voices])if(s.clip){try{s.stop()}catch{}this.voices.delete(s)}}
 cinematicSound(kind){if(!this.running||!this.enabled)return;const c=this.ctx,t=c.currentTime,duration=kind==='engine'?2.7:kind==='skid'?1.45:.35,g=c.createGain(),filter=c.createBiquadFilter();let source;if(kind==='engine'){source=c.createOscillator();source.type='sawtooth';source.frequency.setValueAtTime(55,t);source.frequency.exponentialRampToValueAtTime(145,t+1.45);source.frequency.exponentialRampToValueAtTime(35,t+duration);filter.type='lowpass';filter.frequency.value=450}else{source=c.createBufferSource();const b=c.createBuffer(1,Math.ceil(c.sampleRate*duration),c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(kind==='skid'?.7:1);source.buffer=b;filter.type=kind==='skid'?'bandpass':'lowpass';filter.frequency.value=kind==='skid'?1900:1800}g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(kind==='engine'?.38:.6,t+.035);g.gain.exponentialRampToValueAtTime(.001,t+duration);source.connect(filter);filter.connect(g);g.connect(this.fx);this.voices.add(source);source.onended=()=>{this.voices.delete(source);source.disconnect();filter.disconnect();g.disconnect()};source.start(t);source.stop(t+duration)} 
 play(name,{gain=1,x=480,heavy=false,delay=0,offset=0}={}){if(!this.running||!this.enabled||!this.buffers[name])return;const now=this.ctx.currentTime;if(name.endsWith('-step')&&now-(this.lastVoice[name]??-99)<.09)return;if(name.endsWith('-hurt')&&now-(this.lastVoice[name]??-99)<.12)return;this.lastVoice[name]=now;const s=this.ctx.createBufferSource();s.buffer=this.buffers[name];const g=this.ctx.createGain();g.gain.value=gain;const pan=this.ctx.createStereoPanner();pan.pan.value=Math.max(-.7,Math.min(.7,(x-480)/600));s.connect(g);if(heavy){const bass=this.ctx.createBiquadFilter();bass.type='lowshelf';bass.frequency.value=150;bass.gain.value=3;g.connect(bass);bass.connect(pan);}else g.connect(pan);pan.connect(this.fx);s.onended=()=>{this.voices.delete(s);s.disconnect();g.disconnect();pan.disconnect()};this.voices.add(s);if(/^(intro-|record-|corporate-|escape-|mc-)/.test(name))s.clip={name,gain,x,heavy,offset,started:now+delay};s.start(now+delay,offset)}
 event(e){if(e.type==='pickup'){this.play('charge',{gain:.22,x:e.x});return}if(['elbow','dash'].includes(e.weapon))e={...e,weapon:e.weapon==='elbow'&&e.fighter!=='em'?'punch':'kick'};const voice=e.who==='player'?'player':'enemy';if(e.type==='action'){if(e.weapon==='jump')this.play('jump',{gain:.4,x:e.x});else{this.play(voice+'-effort',{gain:.48,x:e.x});if(e.weapon==='special')this.play('charge',{gain:.7,x:e.x})}}
 if(e.type==='swing')this.play(e.weapon+'-swing',{gain:.7,x:e.x});
 if(e.type==='hit'){if(e.weapon==='special'&&e.fighter==='change')this.play('punch-hit',{gain:e.big?1:.75,x:e.x,heavy:e.big});if(e.weapon!=='special')this.play(e.weapon+'-hit',{gain:1,x:e.x,heavy:true});if(!e.ko)this.play(voice+'-hurt',{gain:.6,x:e.x});if(e.big)this.play('body-fall',{gain:.75,x:e.x,heavy:true,delay:.10})}
 if(e.type==='ko')this.play(voice+'-ko',{gain:.75,x:e.x});
 if(e.type==='step')this.play(voice+'-step',{gain:voice==='player'?.22:.14,x:e.x});
 if(e.type==='land')this.play('land',{gain:.45,x:e.x});
 if(e.type==='shockwave'&&e.fighter==='change'){this.play('punch-swing',{gain:.7,x:e.x});this.play('burst',{gain:.18,x:e.x});return}if(e.type==='shockwave'){this.play(e.fighter==='em'?'kick-hit':'slam',{gain:1,x:e.x,heavy:true});this.play('burst',{gain:.65,x:e.x,delay:.045})}}
}
const fightAudio=new FightAudio();
