let bouncerReady=false,propsReady=false;const enforcerSprites={},shopProps=[];
function loadBouncerArt(){const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const pixels=g.getImageData(0,0,c.width,c.height),d=pixels.data,W=c.width,H=c.height;for(let row=0;row<4;row++){const y0=Math.floor(row*H/4),y1=Math.floor((row+1)*H/4),seen=new Uint8Array(W*(y1-y0)),parts=[];for(let y=y0;y<y1;y++)for(let x=0;x<W;x++){const local=(y-y0)*W+x;if(seen[local]||d[(y*W+x)*4+3]<150)continue;const stack=[y*W+x],part=[];seen[local]=1;let l=x,r=x,t=y,b=y;while(stack.length){const p=stack.pop(),px=p%W,py=Math.floor(p/W);part.push(p);l=Math.min(l,px);r=Math.max(r,px);t=Math.min(t,py);b=Math.max(b,py);for(const n of [p-1,p+1,p-W,p+W]){const nx=n%W,ny=Math.floor(n/W);if(nx<0||nx>=W||ny<y0||ny>=y1||Math.abs(nx-px)>1)continue;const k=(ny-y0)*W+nx;if(!seen[k]&&d[n*4+3]>=150){seen[k]=1;stack.push(n)}}}if(part.length>500)parts.push({l,r,t,b,part})}const chosen=parts.sort((a,b)=>b.part.length-a.part.length).slice(0,6).sort((a,b)=>a.l-b.l);const tier=['white','green','black','gold'][row];enforcerSprites[tier]=chosen.map(v=>{const f=document.createElement('canvas');f.width=v.r-v.l+1;f.height=v.b-v.t+1;const q=f.getContext('2d'),data=q.createImageData(f.width,f.height);for(const p of v.part){const k=((Math.floor(p/W)-v.t)*f.width+p%W-v.l)*4;for(let j=0;j<4;j++)data.data[k+j]=d[p*4+j]}q.putImageData(data,0,0);return f});if(chosen.length!==6)throw Error('Bouncer atlas needs six poses: '+tier)}bouncerReady=true;checkReady()};im.onerror=()=>{$('loading').textContent='Bouncer artwork could not load'};im.src='data:image/png;base64,ENFORCER_DATA'}
function loadShopProps(){const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height).data;for(let i=0;i<4;i++){const x0=i%2*c.width/2,x1=x0+c.width/2,y0=i<2?0:Math.floor(c.height*.73),y1=i<2?Math.floor(c.height*.73):c.height;let l=x1,r=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*c.width+x)*4+3]>100){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const f=document.createElement('canvas');f.width=r-l+1;f.height=b-t+1;f.getContext('2d').drawImage(c,l,t,f.width,f.height,0,0,f.width,f.height);shopProps.push(f)}propsReady=true;checkReady()};im.src='data:image/png;base64,PROPS_DATA'}
function drawCabinet(t){const s=shopProps[0];if(!s)return;ctx.drawImage(s,40,91,86,155);ctx.fillStyle='rgba(61,242,240,'+(.04+.04*Math.sin(t*7))+')';ctx.fillRect(68,126,39,35)}
function drawDoorDebris(){const s=shopProps[1];if(s)ctx.drawImage(s,18,331,151,56)}
function drawBaton(x,y,gold,angle=0,size=66){const s=shopProps[gold?3:2];if(!s)return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.drawImage(s,-size*.17,-5,size,size*s.height/s.width);ctx.restore()}
function drawHeldBaton(a){if(!a.held||['down','defeated','grabbed'].includes(a.action))return;const active=a.action==='baton',u=active?Math.min(1,a.time/.38):0;ctx.save();ctx.translate(a.x,a.y-lab.height(a));ctx.scale(a.face,1);const striking=active&&a.time>.22,x=striking?100:a.kind==='enforcer'?52:a.fighter==='em'||a.fighter==='change'?52:68,y=striking?-164:a.kind==='enforcer'?-105:-149;drawBaton(x,y,a.held.gold,active?-1.6+u*1.8:.8,70);ctx.restore()}
function drawEnforcer(a){const frames=enforcerSprites[a.tier];if(!frames)return;let f=0;if(a.action==='walk')f=[1,0,2,0][Math.floor(a.time/.18)%4];if(['enforcerJab','baton'].includes(a.action)&&a.time>.22)f=3;if(a.action==='enforcerSlam'||a.action==='enforcerBurst'||a.action==='recover')f=4;if(['down','defeated'].includes(a.action))f=5;const s=frames[f],scale=235/frames[0].height;ctx.save();ctx.fillStyle='#10182030';ctx.beginPath();ctx.ellipse(a.x,a.y+2,48,10,0,0,Math.PI*2);ctx.fill();ctx.translate(a.x,a.y-lab.height(a));ctx.scale(a.face,1);if(a.action==='hurt')ctx.rotate(-.12);ctx.drawImage(s,-s.width*scale*.5,-s.height*scale,s.width*scale,s.height*scale);ctx.restore();drawHeldBaton(a);if(MOVES[a.action]&&a.time<lab.moveData(a).start){ctx.fillStyle=a.tier==='gold'?'#ffd65c':'#e89151';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(a.action==='enforcerSlam'?'GRAB!':a.action==='enforcerBurst'?'SHOCKWAVE!':'STRIKE!',a.x,a.y-246)}ctx.fillStyle=a.tier==='gold'?'#ffdc71':'#e5dfcf';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillText(a.tier.toUpperCase()+' · '+a.hp,a.x,a.y-265);const w=60;ctx.fillStyle='#15202a';ctx.fillRect(a.x-w/2,a.y-259,w,4);ctx.fillStyle={white:'#ddd',green:'#779259',black:'#8a8f9d',gold:'#efc344'}[a.tier];ctx.fillRect(a.x-w/2,a.y-259,w*a.hp/a.maxHP,4)}
function drawWeapons(){for(const w of lab.weapons)drawBaton(w.x,w.y,w.gold,-.08,58);const w=lab.nearbyWeapon();if(w&&!lab.attackNearby()){ctx.strokeStyle='#f5d465';ctx.strokeRect(w.x-14,w.y-12,67,28);ctx.fillStyle='#172323';ctx.fillRect(w.x-82,w.y+17,170,21);ctx.fillStyle='#ffe7aa';ctx.font='bold 11px monospace';ctx.textAlign='center';ctx.fillText('J · '+(lab.player.held?'SWAP':'PICK UP')+' BATON',w.x,w.y+31)}const p=lab.player;$('weaponInfo').textContent=p.held?(p.held.gold?'GOLD BATON':'BATON')+' · '+p.held.hits+' / '+p.held.max+' · J ATTACK':'UNARMED';$('enemyName').textContent=lab.enemies.some(e=>e.kind==='enforcer')?'CORPORATE + ENFORCERS':'CORPORATE BULLY'}
const originalAudioEvent=FightAudio.prototype.event;FightAudio.prototype.event=function(e){if(['weaponDrop','weaponPickup','weaponBreak'].includes(e.type)){this.play('case-hit',{gain:.3,x:e.x});return}const names={baton:'case',enforcerJab:'punch',enforcerSlam:'case',enforcerBurst:'special'};return originalAudioEvent.call(this,names[e.weapon]?{...e,weapon:names[e.weapon]}:e)};
loadBouncerArt();loadShopProps();
