const MOVES={
 elbow:{duration:.52,start:.14,end:.27,reach:92,depth:26,damage:18,force:170},
 dash:{duration:.62,start:.04,end:.34,reach:78,depth:24,damage:20,force:310,knockdown:true},
 punch:{duration:.40,start:.16,end:.26,reach:123,depth:24,damage:9,force:110},
 kick:{duration:.65,start:.235,end:.40,reach:154,depth:26,damage:15,force:205},
 special:{duration:1.02,start:.495,end:.64,reach:300,depth:105,damage:40,force:390,knockdown:true},
 phone:{duration:.90,start:.38,end:.51,reach:133,depth:23,damage:10,force:125},
 case:{duration:1.30,start:.65,end:.83,reach:162,depth:28,damage:18,force:235,knockdown:true}
};
const DEFAULTS={playerSpeed:145,enemySpeed:90,tempo:1,aggression:.65,reach:1,damage:1,stun:.32,knockback:1,dashSpeed:600,elbowDamage:18,blastRadius:300,recordsNeeded:3};
class CombatLab{
 constructor(){this.character='promis';this.settings={...DEFAULTS};this.enemyMode='fight';this.god=true;this.reset()}
 selectCharacter(name){if(!['promis','em','bully','change'].includes(name))return false;this.character=name;this.reset();return true}
 get playerName(){return this.character==='change'?'DJ Change':this.character==='bully'?'DJ Bully':this.character==='em'?'DJ Em':'DJ Promis'}
 get enemy(){return this.enemies.find(e=>e.hp>0)||this.enemies[0]}
 spawnWave(){const n=Math.min(this.wave,3);this.enemies=Array.from({length:n},(_,i)=>{const x=this.wave===1?665:i%2?-50:1010;const e=this.make('enemy',x,x<480?1:-1);e.uid=this.wave+'-'+i;e.y=this.wave===1?367:[335,397,365][i];e.entering=this.wave>1;e.cooldown=1.5+i*.6;return e});this.waveDelay=null;this.nextAttack=this.clock+1;this.message='WAVE '+this.wave+' · '+n+' '+(n===1?'bully':'bullies')}
 make(id,x,face){return {id,uid:id,flight:null,airAttack:false,fighter:id==='player'?this.character:null,kickCount:0,kickVariant:0,punchCount:0,hand:0,distance:0,hitTargets:new Set(),x,y:367,face,action:'idle',time:0,hp:100,vx:0,invuln:0,cooldown:id==='enemy'?1.5:0,hit:false,impact:false,serial:0,chain:0}}
 reset(){this.grabTarget=null;this.grabAttempted=false;this.player=this.make('player',300,1);this.events=[];this.queue=null;this.over=false;this.clock=0;this.wave=1;this.kills=0;this.hits={player:0,enemy:0};this.inspect=null;this.charge=0;this.vinyl=[];this.vinylTimer=4;this.dashCooldown=0;this.spawnWave();for(let i=0;i<3;i++)this.spawnVinyl()}

 spawnVinyl(){if(this.vinyl.length>=5)return;let v;for(let i=0;i<30;i++){v={x:(this.bounds?.left??135)+30+Math.random()*((this.bounds?.right??825)-(this.bounds?.left??135)-60),y:(this.lane?.[0]??280)+10+Math.random()*((this.lane?.[1]??435)-(this.lane?.[0]??280)-20)};if(this.vinyl.every(r=>Math.hypot(r.x-v.x,(r.y-v.y)*2)>75))break}this.vinyl.push(v)}
 nearbyVinyl(){return this.vinyl.find(v=>Math.abs(v.x-this.player.x)<40&&Math.abs(v.y-this.player.y)<23)}
 dash(direction){if(this.dashCooldown>0||this.player.flight!==null||!['idle','walk'].includes(this.player.action)||this.over)return false;this.player.face=direction;this.dashCooldown=1.05;return this.trigger('dash')}
 moveData(a){const m=MOVES[a.action];if(!m)return null;if(a.fighter==='change'){const phase=a.time<.38?0:a.time<.60?1:2;const variants={punch:{duration:.30,start:.10,end:.18,damage:7,force:65},kick:{duration:.34,start:.11,end:.21,damage:10,force:60},elbow:{duration:.40,start:.12,end:.24,damage:this.settings.elbowDamage-3,force:145},dash:{duration:.52,start:.20,end:.34,damage:16,force:285,reach:125},special:{duration:1.05,start:[.18,.38,.60][phase],end:[.28,.48,.78][phase],reach:145,depth:30,damage:phase===2?26:8,force:phase===2?340:35,knockdown:phase===2}};return {...m,...variants[a.action]}}if(a.fighter==='bully'){const variants={punch:{duration:.52,start:.21,end:.34,damage:14,force:165},kick:{duration:.76,start:.28,end:.46,damage:22,force:270},elbow:{duration:.68,start:.28,end:.43,damage:this.settings.elbowDamage+8,force:280,knockdown:true},dash:{duration:.70,damage:28,force:370},special:{duration:1.40,start:.76,end:.92,damage:50,force:460,reach:this.settings.blastRadius}};return {...m,...variants[a.action]}}if(a.fighter==='em'){const variants={punch:{duration:.36,start:.13,end:.23,damage:8},kick:a.kickVariant?{duration:.66,start:.25,end:.40,reach:165,damage:19,force:250}:{duration:.48,start:.17,end:.29,reach:145,damage:13,force:165},elbow:{duration:.48,start:.13,end:.25,reach:82,damage:this.settings.elbowDamage+2,force:210},dash:{damage:23,reach:125},special:{duration:1.12,start:.43,end:.91,reach:this.settings.blastRadius,depth:70,damage:42,force:440}};return {...m,...variants[a.action]}}return {...m,damage:a.action==='elbow'?this.settings.elbowDamage:m.damage,reach:a.action==='special'?this.settings.blastRadius:m.reach}}
 releaseGrab(){if(this.grabTarget){const e=this.grabTarget;this.grabTarget=null;e.grabbedBy=false;this.set(e,'idle')}}
 set(a,action){if(a.id==='player'){if(action!=='special')this.releaseGrab();else this.grabAttempted=false}a.action=action;a.time=0;a.hit=false;a.impact=false;a.serial++;a.hitTargets=new Set();a.burstPhase=-1;if(action==='jump'){a.flight=0;a.airAttack=false}if(action==='kick')a.kickVariant=a.kickCount++%2;if(action==='punch')a.hand=a.punchCount++%2;if(MOVES[action]||action==='jump')this.events.push({type:'action',weapon:action,fighter:a.fighter,who:a.id,x:a.x})}
 trigger(action){if(this.over)return false;this.inspect=null;const p=this.player;if(p.flight!==null){if(!p.airAttack&&['jump','airborne'].includes(p.action)&&['punch','kick'].includes(action)){p.airAttack=true;this.set(p,action);return true}return false}if(action==='elbow'&&['punch','kick'].includes(p.action)&&p.time<.14){this.queue=null;this.set(p,'elbow');return true}if(['idle','walk'].includes(p.action)){if(action==='punch'&&this.nearbyVinyl()){if(this.charge>=this.settings.recordsNeeded){this.message='SPECIAL READY · press L';return true}this.vinyl.splice(this.vinyl.indexOf(this.nearbyVinyl()),1);this.charge++;this.set(p,'pickup');this.events.push({type:'pickup',who:'player',x:p.x});this.message='RARE VINYL · '+this.charge+' / '+this.settings.recordsNeeded;return true}if(action==='special'){if(this.charge<this.settings.recordsNeeded){this.message='Collect '+(this.settings.recordsNeeded-this.charge)+' more rare vinyl · J to pick up';return false}this.charge=0;p.invuln=p.fighter==='bully'?1.4:1.05}this.set(p,action);p.chain=action==='punch'?1:0;return true}if(['em','change'].includes(p.fighter)&&p.action==='kick'&&action==='kick'){this.queue='kick';return true}if(p.action==='punch'&&action==='punch'){this.queue='punch';return true}return false}
 duration(a){return this.moveData(a)?.duration??({grabbed:Infinity,pickup:.32,jump:.71,hurt:this.settings.stun,down:1.05,recover:.42,defeated:Infinity,walk:.72,idle:.96}[a.action]??1)}
 height(a){if(a.dropRemaining>0)return 400*Math.min(1,a.dropRemaining/.85);if(a.grabbedBy){const t=this.player.time;return t<.6?Math.min(1,Math.max(0,(t-.25)/.22))*80:80*Math.max(0,1-(t-.6)/.16)}return a.flight!==null?Math.sin(Math.min(1,(this.inspect?a.time:a.flight)/.71)*Math.PI)*89:0}
 area(a){const m=this.moveData(a);if(!m)return null;const reach=m.reach*this.settings.reach;if(a.action==='special'&&a.fighter==='em'){const progress=Math.max(0,Math.min(1,(a.time-m.start)/(m.end-m.start))),extent=Math.max(75,reach*progress);return {x:a.face>0?a.x+10:a.x-extent,y:a.y-m.depth,w:extent-10,h:m.depth*2,radial:false}}if(a.action==='special'&&a.fighter!=='change'){const depth=reach*.35;return {x:a.x-reach,y:a.y-depth,w:reach*2,h:depth*2,radial:true}}return {x:a.face>0?a.x+10:a.x-reach,y:a.y-m.depth,w:reach-10,h:m.depth*2,radial:false}}
 inRange(a,b){const r=this.area(a);if(!r||['down','recover','defeated'].includes(b.action)||b.invuln>0||this.height(b)>38)return false;if(r.radial)return Math.hypot((b.x-a.x)/(r.w/2),(b.y-a.y)/(r.h/2))<=1;const forward=(b.x-a.x)*a.face;return forward>=10&&forward<=r.w+10&&Math.abs(b.y-a.y)<=r.h/2}
 hit(a,b){const m=this.moveData(a);if(a.hitTargets.has(b.uid)||!this.inRange(a,b))return false;a.hit=true;a.hitTargets.add(b.uid);const weapon=a.action;const damage=Math.round(m.damage*this.settings.damage);if(!(b.id==='player'&&this.god))b.hp=Math.max(0,b.hp-damage);b.vx=(Math.sign(b.x-a.x)||a.face)*m.force*this.settings.knockback;b.invuln=.12;this.queue=b.id==='player'?null:this.queue;this.set(b,b.hp===0?'defeated':m.knockdown?'down':'hurt');b.cooldown=.6;this.hits[a.id]++;this.events.push({type:'hit',x:b.x,y:b.y-135,damage,big:m.knockdown||b.hp===0,fighter:a.fighter,who:b.id,weapon,ko:b.hp===0});this.message=(a.id==='player'?this.playerName:a.kind==='enforcer'?ENFORCERS[a.tier].name:'Corporate Bully')+' landed '+({case:'briefcase swing',phone:'phone strike',special:a.fighter==='change'?'Tempo Burst':a.fighter==='bully'?'Bass-Slam Drop':a.fighter==='em'?'Synaptic Kick':'shockwave',elbow:a.fighter==='change'?'turning backfist':a.fighter==='bully'?'hammer blow':a.fighter==='em'?'rising knee':'elbow',dash:a.fighter==='change'?'dash thrust':a.fighter==='bully'?'shoulder charge':a.fighter==='em'?'advancing kick':'dash'}[a.action]||a.action)+' · '+damage+' damage';if(b.hp===0){if(b.id==='enemy')this.kills++;else{this.over=true;this.message=this.playerName.toUpperCase()+' DOWN — R to reset'}this.events.push({type:'ko',who:b.id,x:b.x})}return true}
 move(a,dx,dy,speed,dt){const n=Math.hypot(dx,dy)||1,ox=a.x,oy=a.y;if(dx)a.face=Math.sign(dx);a.x=Math.max(a.entering?(this.bounds?.left??135)-200:(this.bounds?.left??135),Math.min(a.entering?(this.bounds?.right??825)+200:(this.bounds?.right??825),a.x+dx/n*speed*dt));a.y=Math.max(this.lane?.[0]??280,Math.min(this.lane?.[1]??435,a.y+dy/n*speed*.55*dt));const distance=Math.hypot(a.x-ox,(a.y-oy)/.55);if(a.flight===null){if(distance>.00001){if(a.action!=='walk')this.set(a,'walk');const before=Math.floor(a.distance/52);a.distance+=distance;if(Math.floor(a.distance/52)>before)this.events.push({type:'step',who:a.id,x:a.x});a.time=(a.time+distance/145)%.72}else if(a.action==='walk')this.set(a,'idle')}}
 update(dt,input={}){for(let left=dt;left>1e-8;left-=1/120)this.tick(Math.min(left,1/120),input)}
 tick(dt,input){this.clock+=dt;const p=this.player,e=this.enemy;if(this.inspect){const a=this.inspect.actor==='enemy'?e:p;a.time=(a.time+dt*(a.id==='enemy'?this.settings.tempo:1))%this.duration(a);return}
 this.dashCooldown=Math.max(0,this.dashCooldown-dt);if(!this.over){this.vinylTimer-=dt;if(this.vinylTimer<=0){this.spawnVinyl();this.vinylTimer=5+Math.random()*3}if(p.action==='dash'&&p.time<.34)p.x=Math.max(this.bounds?.left??135,Math.min(this.bounds?.right??825,p.x+p.face*this.settings.dashSpeed*(p.fighter==='change'?1.15:p.fighter==='bully'?.85:1)*dt))}
 if(!this.over&&p.fighter==='change'&&p.action==='special'){
 const phase=p.time<.38?0:p.time<.60?1:2;if(phase!==p.burstPhase){p.burstPhase=phase;p.hitTargets=new Set();p.impact=false}
 if(p.time>=.12&&p.time<.60){let distance=this.settings.dashSpeed*.95*dt;for(const foe of this.enemies){const gap=(foe.x-p.x)*p.face;if(foe.hp>0&&!['down','defeated'].includes(foe.action)&&Math.abs(foe.y-p.y)<30&&gap>0)distance=Math.min(distance,Math.max(0,gap-95))}p.x=Math.max(this.bounds?.left??135,Math.min(this.bounds?.right??825,p.x+p.face*distance))}
 }
 for(const a of [p,...this.enemies]){if(a.flight!==null){a.flight+=dt;if(a.flight>=.71){a.flight=null;this.events.push({type:'land',who:a.id,x:a.x});if(['jump','airborne','punch','kick'].includes(a.action))this.set(a,'idle');if(a===p)this.queue=null}}a.invuln=Math.max(0,a.invuln-dt);a.cooldown=Math.max(0,a.cooldown-dt);a.x=Math.max(a.entering?(this.bounds?.left??135)-200:(this.bounds?.left??135),Math.min(a.entering?(this.bounds?.right??825)+200:(this.bounds?.right??825),a.x+a.vx*dt));a.vx*=Math.exp(-11*dt);if(a.action!=='walk')a.time+=dt*(a.id==='enemy'&&MOVES[a.action]?this.settings.tempo:1)}
 if(!this.over){if(['idle','walk','jump','airborne'].includes(p.action)||(p.flight!==null&&['punch','kick'].includes(p.action)))this.move(p,input.dx||0,input.dy||0,this.settings.playerSpeed*(p.fighter==='change'?1.14:p.fighter==='bully'?.86:1)*(input.run?1.62:1),dt);
 for(const e of this.enemies){if(e.hp<=0)continue;if(e.entering&&e.x>=(this.bounds?.left??135)&&e.x<=(this.bounds?.right??825))e.entering=false;if(['idle','walk'].includes(e.action)){const dx=p.x-e.x,dy=p.y-e.y;e.face=Math.sign(dx)||e.face;if(this.enemyMode!=='target'||e.entering){const gap=this.enemyMode==='follow'?108:Math.min(103,MOVES.phone.reach*this.settings.reach*.85);if(e.entering||Math.abs(dx)>gap||Math.abs(dy)>8)this.move(e,e.entering?(e.x<(this.bounds?.left??135)?1:-1):Math.abs(dx)>gap?Math.sign(dx):0,Math.abs(dy)>8?Math.sign(dy):0,this.settings.enemySpeed*(e.kind==='enforcer'?ENFORCERS[e.tier].speed:1),dt);else{if(e.action==='walk')this.set(e,'idle');if(this.enemyMode==='fight'&&e.cooldown===0&&this.settings.aggression>0&&this.clock>=this.nextAttack){this.set(e,e.kind==='enforcer'?(e.held?'baton':['black','gold'].includes(e.tier)&&e.chain%3===2?'enforcerBurst':e.chain%2?'enforcerSlam':'enforcerJab'):(e.chain%2?'case':'phone'));e.chain++;this.nextAttack=this.clock+1.05/this.settings.tempo;this.events.push({type:'windup',weapon:e.action});e.cooldown=(1.5-this.settings.aggression*1.2)}}}else if(e.action==='walk')this.set(e,'idle')}}
 if(p.fighter==='bully'&&p.action==='special'){if(!this.grabAttempted&&p.time>=.25){this.grabAttempted=true;const candidates=this.enemies.filter(e=>e.hp>0&&!['down','recover','defeated','grabbed'].includes(e.action)&&e.invuln<=0&&(e.x-p.x)*p.face>0&&(e.x-p.x)*p.face<145&&Math.abs(e.y-p.y)<30).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x));if(candidates[0]){this.grabTarget=candidates[0];this.set(this.grabTarget,'grabbed');this.grabTarget.grabbedBy=true;this.grabTarget.vx=0;this.grabTarget.flight=null}}if(this.grabTarget){this.grabTarget.x=p.x+p.face*105;this.grabTarget.y=p.y;this.grabTarget.face=-p.face;if(p.time>=.76)this.releaseGrab()}}
 for(const a of [p,...this.enemies]){const m=this.moveData(a);if(!m)continue;if(a.time>=m.start&&!a.impact){a.impact=true;this.events.push({type:a.action==='special'?'shockwave':'swing',x:a.action==='special'?a.x:a.x+a.face*35,y:a.y,fighter:a.fighter,face:a.face,radius:a.action==='special'?this.settings.blastRadius*this.settings.reach:0,weapon:a.action,who:a.id})}if(a.time>=m.start&&a.time<=m.end)for(const b of a===p?this.enemies:[p]){this.hit(a,b);if(this.over)break}}
 // Prevent bodies walking through each other on the same floor lane.
 for(const e of this.enemies){if(Math.abs(p.y-e.y)<18&&this.height(p)<20&&!['down','defeated','grabbed'].includes(e.action)&&Math.abs(p.x-e.x)<48){const sign=Math.sign(p.x-e.x)||-p.face,overlap=48-Math.abs(p.x-e.x);p.x=Math.max(this.bounds?.left??135,Math.min(this.bounds?.right??825,p.x+sign*overlap/2));e.x=Math.max(this.bounds?.left??135,Math.min(this.bounds?.right??825,e.x-sign*overlap/2))}}
 }
 for(const a of [p,...this.enemies]){if(a.flight!==null&&['jump','airborne'].includes(a.action))continue;if(a.time<this.duration(a))continue;if(['idle','walk'].includes(a.action)){a.time%=this.duration(a);continue}if(a.action==='defeated')continue;if(a.action==='down'){this.set(a,'recover');a.invuln=.6;continue}if(a.action==='recover'){this.set(a,'idle');a.invuln=.2;continue}if(a===p&&a.flight===null&&['punch','kick'].includes(a.action)&&this.queue&&!this.over){const queued=this.queue;this.queue=null;this.set(p,queued);p.chain=p.chain%3+1}else{this.set(a,a.flight!==null?'airborne':'idle');if(a.id==='enemy')a.cooldown=Math.max(a.cooldown,(1.5-this.settings.aggression*1.2)/this.settings.tempo)}}
 if(!this.campaignActive&&!this.over&&this.enemies.every(e=>e.hp===0)){if(this.waveDelay===null){this.waveDelay=2.2;this.message='WAVE '+this.wave+' CLEAR · next group incoming'}else{this.waveDelay-=dt;if(this.waveDelay<=0){this.wave++;this.spawnWave()}}}

 }
}
if(typeof module!=='undefined')module.exports={CombatLab,MOVES,DEFAULTS};
