'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),keys=new Set(),sprites=[],emSprites=[],bullySprites=[],changeSprites=[],enemySprites=[];
const gestures=new CombatGestures();const lab=new CombatLab();let starting=false,runToken=0,started=false;let ready=false,changeLoaded=false,bullyLoaded=false,emLoaded=false,emWalkLoaded=false,shopLoaded=false,actionsLoaded=false,movesLoaded=false,walkLoaded=false,enemyLoaded=false,paused=true,speed=1.3,sound=false,audioCtx=null,last=0,particles=[],rings=[],popups=[],shake=0,showBoxes=false;
const sequences={elbow:{frames:[36,37,38],times:[.14,.13,.25]},dash:{frames:[39,40,39,40,0],times:[.085,.085,.085,.085,.28]},pickup:{frames:[41],times:[.32]},idle:{frames:[0,5],times:[.48,.48]},walk:{frames:[24,25,26,27],times:[.18,.18,.18,.18]},punch:{frames:[6,7,8,9,10,11],times:[.045,.075,.045,.10,.07,.065]},kick:{frames:[12,13,14,15,16,17],times:[.05,.12,.065,.16,.10,.10]},special:{frames:[18,19,20,21,22,23],times:[.16,.25,.085,.095,.24,.19]},jump:{frames:[32,33,32],times:[.18,.35,.18]},airborne:{frames:[32,33,32],times:[.18,.35,.18]},hurt:{frames:[6],times:[1]},down:{frames:[6],times:[2]},defeated:{frames:[6],times:[10]},recover:{frames:[20,23],times:[.21,.21]}};
const punchHands=[{frames:[28,29,28,0],times:[.16,.10,.08,.06]},{frames:[30,31,30,0],times:[.16,.10,.08,.06]}];
const emSequences={idle:{frames:[0,20],times:[.48,.48]},walk:{frames:[24,25,26,27],times:[.18,.18,.18,.18]},elbow:{frames:[8,12,0],times:[.13,.15,.20]},dash:{frames:[13,16,11],times:[.17,.17,.28]},pickup:{frames:[23],times:[.32]},special:{frames:[17,18,19,10,20],times:[.20,.23,.25,.23,.21]},jump:{frames:[14],times:[.71]},airborne:{frames:[14],times:[.71]},hurt:{frames:[21],times:[1]},down:{frames:[22],times:[2]},defeated:{frames:[22],times:[10]},recover:{frames:[23,20],times:[.21,.21]}};
const bullySequences={...emSequences,walk:{frames:[1,2,3,4],times:[.18,.18,.18,.18]},elbow:{frames:[12,19,20],times:[.28,.15,.25]},dash:{frames:[13,17,20],times:[.20,.14,.36]},special:{frames:[17,18,18,19,20],times:[.25,.35,.16,.20,.44]}};
const changeSequences={...emSequences,walk:{frames:[1,2,3,4],times:[.18,.18,.18,.18]},elbow:{frames:[5,12,20],times:[.12,.12,.16]},dash:{frames:[13,19,20],times:[.20,.14,.18]},special:{frames:[17,18,6,18,7,18,19,20],times:[.12,.06,.10,.10,.10,.12,.18,.27]}};
function actorSequence(a){if(a.fighter==='change'){if(a.action==='punch')return {frames:a.flight!==null?[14,15,14]:[5,a.hand?7:6,20],times:[.10,.08,.12]};if(a.action==='kick')return {frames:a.flight!==null?[14,16,14]:[8,a.kickVariant?10:9,11],times:[.11,.10,.13]};return changeSequences[a.action]||changeSequences.idle}if(a.fighter==='bully'){if(a.action==='punch')return {frames:a.flight!==null?[14,15,14]:[5,a.hand?7:6,20],times:[.21,.13,.18]};if(a.action==='kick')return {frames:a.flight!==null?[14,16,14]:[8,9,11,20],times:a.flight!==null?[.28,.18,.30]:[.28,.18,.16,.14]};return bullySequences[a.action]||bullySequences.idle}if(a.fighter==='em'){if(a.action==='punch')return {frames:a.flight!==null?[14,15,14]:[5,a.hand?7:6,0],times:[.13,.10,.13]};if(a.action==='kick'){if(a.flight!==null)return {frames:[14,16,14],times:[.17,.23,.26]};return a.kickVariant?{frames:[8,10,11,0],times:[.25,.15,.14,.12]}:{frames:[8,9,11,0],times:[.17,.12,.10,.09]}}return emSequences[a.action]||emSequences.idle}if(a.action==='punch'){if(a.flight!==null)return {frames:[32,34+a.hand,32],times:[.16,.10,.14]};return punchHands[a.hand]}if(a.action==='kick'&&a.flight!==null)return {frames:[32,13,14,15,32],times:[.08,.155,.10,.10,.215]};return sequences[a.action]||sequences.idle}
function frameAt(a,t){const seq=typeof a==='object'?actorSequence(a):sequences[a]||sequences.idle;let sum=0;for(let i=0;i<seq.times.length;i++){sum+=seq.times[i];if(t<sum)return {sprite:seq.frames[i],index:i}}return {sprite:seq.frames.at(-1),index:seq.frames.length-1}}
function checkReady(){ready=!!sprites[0]&&walkLoaded&&enemyLoaded&&shopLoaded&&actionsLoaded&&movesLoaded&&emLoaded&&emWalkLoaded&&bullyLoaded&&changeLoaded;if(ready){$('loading').classList.add('hidden');draw()}}

function input(){return {dx:Number(keys.has('ArrowRight')||keys.has('KeyD'))-Number(keys.has('ArrowLeft')||keys.has('KeyA')),dy:Number(keys.has('ArrowDown')||keys.has('KeyS'))-Number(keys.has('ArrowUp')||keys.has('KeyW')),run:keys.has('ShiftLeft')||keys.has('ShiftRight')}}
function collectEvents(){for(const e of lab.events.splice(0)){if(!lab.inspect)fightAudio.event(e);if(e.type==='shockwave'){rings.push({...e,age:0});shake=10}if(e.type==='hit'){shake=e.big?5:2;popups.push({...e,age:0});for(let i=0;i<12;i++){const angle=i*2.4;particles.push({x:e.x,y:e.y,vx:Math.cos(angle)*(35+i*6),vy:Math.sin(angle)*85,age:0})}}}}
function update(dt){lab.update(dt,input());collectEvents();particles.forEach(p=>{p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=190*dt});particles=particles.filter(p=>p.age<.3);rings.forEach(r=>r.age+=dt);rings=rings.filter(r=>r.age<.7);popups.forEach(p=>p.age+=dt);popups=popups.filter(p=>p.age<.75);shake=Math.max(0,shake-dt*25)}
function enemyFrame(e){switch(e.action){case'walk':return [1,2,3,2][Math.floor(e.time/.18)%4];case'phone':return e.time<.38?4:e.time<.59?5:0;case'case':return e.time<.65?6:e.time<.95?7:0;case'grabbed':return 8;case'hurt':return e.time<lab.settings.stun*.65?8:9;case'down':case'defeated':return 10;case'recover':return 11;default:return 0}}
function drawActor(a){const foe=a.id==='enemy',f=foe?enemyFrame(a):frameAt(a,a.flight!==null&&['jump','airborne'].includes(a.action)?(lab.inspect?a.time:a.flight):a.time).sprite,s=(foe?enemySprites:a.fighter==='change'?changeSprites:a.fighter==='bully'?bullySprites:a.fighter==='em'?emSprites:sprites)[f];if(!s)return;const jump=lab.height(a);ctx.fillStyle='#303f3420';ctx.beginPath();ctx.ellipse(a.x,a.y+2,48-jump*.15,9-jump*.025,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(Math.round(a.x),Math.round(a.y-jump));ctx.scale(a.face,1);if(!foe&&a.fighter==='promis'&&['down','defeated'].includes(a.action)){ctx.translate(-90,-14);ctx.rotate(Math.PI/2)}else if(!foe&&a.action==='hurt')ctx.rotate(-.10);if(a.invuln>0&&a.action==='hurt')ctx.filter='brightness(1.5)';ctx.drawImage(s.canvas,Math.round((s.left-s.anchor)*.93),Math.round(-s.height*.93),Math.round(s.width*.93),Math.round(s.height*.93));ctx.restore();if(foe&&['phone','case'].includes(a.action)&&a.time<MOVES[a.action].start){ctx.fillStyle='#db653b';ctx.font='bold 15px monospace';ctx.textAlign='center';ctx.fillText(a.action==='phone'?'PHONE !':'CASE !!',a.x,a.y-250)}}
function oldRing(r){const t=r.age/.7;ctx.globalAlpha=1-t;ctx.fillStyle='#2dd6ed';for(let i=0;i<100;i++){let a=i*Math.PI*2/100;ctx.fillRect(Math.round(r.x+Math.cos(a)*(25+t*210)),Math.round(r.y+Math.sin(a)*(8+t*52)),4,3)}ctx.globalAlpha=1}
function ring(r){if(r.fighter==='change')return;if(r.fighter==='bully'){ctx.save();const t=r.age/.7;ctx.globalAlpha=1-t;ctx.strokeStyle='#3f3930';ctx.lineWidth=3;for(let i=0;i<12;i++){const angle=i*2.399;ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x+Math.cos(angle)*80,r.y+Math.sin(angle)*24);ctx.lineTo(r.x+Math.cos(angle+.12)*150,r.y+Math.sin(angle+.12)*48);ctx.stroke();ctx.fillStyle='#b59e78';const dist=30+t*170;ctx.fillRect(r.x+Math.cos(angle)*dist,r.y+Math.sin(angle)*dist*.35-Math.sin(t*Math.PI)*40,10,8)}ctx.restore()}if(r.fighter==='em'){const t=r.age/.7,x=r.x+r.face*r.radius*Math.min(1,r.age/.48);ctx.save();ctx.globalAlpha=1-t;ctx.strokeStyle='#65eaff';ctx.shadowColor='#14bfff';ctx.shadowBlur=22;ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(x,r.y-94,30,96,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#edffff';ctx.lineWidth=2;for(let j=0;j<6;j++){ctx.beginPath();for(let i=0;i<8;i++){const px=x+(i%2?12:-12)+Math.sin(i*13+j*7+r.age*32)*13,py=r.y-185+i*25; i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.stroke()}ctx.strokeStyle='#47d7ff';ctx.beginPath();ctx.ellipse(x,r.y,65,23,0,0,Math.PI*2);ctx.stroke();ctx.restore();return}const t=Math.min(1,r.age/.7),radius=r.radius||300;ctx.save();ctx.globalAlpha=1-t;for(let layer=0;layer<3;layer++){const progress=Math.max(0,Math.min(1,t*2-layer*.16)),rx=radius*progress;ctx.strokeStyle=layer%2?'#edffff':'#28d9ff';ctx.lineWidth=8-layer*2;ctx.shadowColor='#32cfff';ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(r.x,r.y,rx,rx*.35,0,0,Math.PI*2);ctx.stroke()}ctx.shadowBlur=0;ctx.fillStyle='#bdfaff';ctx.globalAlpha=Math.max(0,.22-t);ctx.beginPath();ctx.ellipse(r.x,r.y,radius,radius*.35,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=(1-t)*.8;for(let i=0;i<28;i++){const a=i*2.399,dist=radius*t;ctx.fillRect(r.x+Math.cos(a)*dist,r.y+Math.sin(a)*dist*.35-Math.sin(t*Math.PI)*(20+i%5*10),4,7)}ctx.restore()}
function drawVinyl(){for(const v of lab.vinyl){ctx.save();ctx.translate(v.x,v.y);ctx.fillStyle='#00ddff25';ctx.beginPath();ctx.ellipse(0,1,24,12,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#171e29';ctx.strokeStyle='#dcb665';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,16,9,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#e8bd5c';ctx.beginPath();ctx.ellipse(0,0,6,3.5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-1,-1,2,2);ctx.fillStyle='#ffe799';ctx.fillRect(18,-16+Math.sin(lab.clock*4)*3,3,3);ctx.restore()}const v=lab.nearbyVinyl();if(v&&lab.player.flight===null){ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillStyle='#15201eea';ctx.fillRect(v.x-64,v.y+14,128,21);ctx.fillStyle='#ffe19b';ctx.fillText(lab.charge>=lab.settings.recordsNeeded?'L · SPECIAL READY':'J · PICK UP VINYL',v.x,v.y+29)}}
function drawBoxes(a){ctx.strokeStyle=a.id==='player'?'#277b4c':'#aa513c';ctx.lineWidth=1;ctx.strokeRect(a.x-24,a.y-18,48,36);const r=lab.area(a);if(r){const m=lab.moveData(a),active=a.time>=m.start&&a.time<=m.end;ctx.strokeStyle=active?'#e5482c':'#ca9c45';ctx.fillStyle=active?'#e5482c28':'#ca9c4512';if(r.radial){ctx.beginPath();ctx.ellipse(a.x,a.y,r.w/2,r.h/2,0,0,Math.PI*2);ctx.fill();ctx.stroke()}else{ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeRect(r.x,r.y,r.w,r.h)}}}
function draw(){ctx.setTransform(canvas.width/960,0,0,canvas.height/470,0,0);ctx.imageSmoothingEnabled=false;ctx.fillStyle='#fff';ctx.fillRect(0,0,960,470);if(shopCanvas)ctx.drawImage(shopCanvas,0,0,960,470);ctx.save();if(shake)ctx.translate(Math.sin(lab.clock*90)*shake,0);drawVinyl();rings.forEach(ring);if(lab.player.fighter==='change'&&['dash','special'].includes(lab.player.action)&&lab.player.time>.12&&lab.player.time<.8){for(let i=3;i>=1;i--){ctx.save();ctx.globalAlpha=.16*(1-i/4);ctx.filter='sepia(1) saturate(4) hue-rotate(135deg)';drawActor({...lab.player,x:lab.player.x-lab.player.face*i*25});ctx.restore()}ctx.save();ctx.strokeStyle='#6deaff';ctx.globalAlpha=.65;ctx.lineWidth=2;for(let i=0;i<5;i++){const x=lab.player.x-lab.player.face*(30+i*8),y=lab.player.y-65-i*25;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-lab.player.face*(45+i*8),y);ctx.stroke()}ctx.restore()}[lab.player,...lab.enemies].filter(a=>a.action!=='defeated'||a.time<1.8).sort((a,b)=>a.y-b.y).forEach(drawActor);particles.forEach(p=>{ctx.globalAlpha=1-p.age/.3;ctx.fillStyle='#dd743d';ctx.fillRect(p.x,p.y,3,3)});ctx.globalAlpha=1;popups.forEach(p=>{ctx.fillStyle=p.who==='enemy'?'#fff0a5':'#ff8a67';ctx.font='bold 17px monospace';ctx.textAlign='center';ctx.fillText('-'+p.damage,p.x,p.y-35-p.age*35)});if(showBoxes){drawBoxes(lab.player);lab.enemies.forEach(drawBoxes)}ctx.restore();$('specialPower').max=lab.settings.recordsNeeded;$('specialPower').value=Math.min(lab.charge,lab.settings.recordsNeeded);$('specialText').textContent=lab.charge>=lab.settings.recordsNeeded?(lab.character==='change'?'L · TEMPO BURST READY':lab.character==='bully'?'L · BASS-SLAM READY':lab.character==='em'?'L · SYNAPTIC KICK READY':'L · SHOCKWAVE READY'):'RARE VINYL '+lab.charge+' / '+lab.settings.recordsNeeded;$('action').textContent=(lab.player.flight!==null?'AIR / ':'')+lab.player.action.toUpperCase()+(lab.player.action==='punch'?' / '+(lab.player.hand?'LEFT':'RIGHT'):'');$('enemyAction').textContent='WAVE '+lab.wave+' · '+lab.enemies.filter(e=>e.hp>0).length+' REMAIN';$('playerHealth').value=lab.player.hp;$('enemyHealth').max=lab.enemies.length*100;$('enemyHealth').value=lab.enemies.reduce((n,e)=>n+e.hp,0);$('playerHP').textContent=lab.player.hp+' / 100';$('enemyHP').textContent=lab.enemies.reduce((n,e)=>n+e.hp,0)+' / '+lab.enemies.length*100;$('fightMessage').textContent=lab.message;$('status').textContent=lab.inspect?'INSPECTING · COMBAT FROZEN':lab.over?'ROUND OVER':paused?'PAUSED':lab.enemyMode.toUpperCase()+' MODE';$('hits').textContent='WAVE '+lab.wave+' · KOs '+lab.kills+' · HITS '+lab.hits.player+' : '+lab.hits.enemy;$('flip').textContent=lab.player.face===1?'Face ←':'Face →';const f=frameAt(lab.player,lab.player.time),seq=actorSequence(lab.player),t=$('timeline');if(t.children.length!==seq.frames.length)t.replaceChildren(...seq.frames.map(()=>{const d=document.createElement('div');d.className='tick';return d}));Array.from(t.children).forEach((d,i)=>d.classList.toggle('on',i===f.index))}
function syncPause(){$('pause').textContent=paused?'Play':'Pause';$('pause').classList.toggle('active',paused)}
async function startTest(){if(!ready||starting)return;const ticket=++runToken;starting=true;$('pause').textContent='Loading audio…';try{await fightAudio.prepare()}catch(e){$('audioStatus').textContent='Audio unavailable; test remains playable.'}if(ticket!==runToken)return;starting=false;started=true;paused=false;if(!lab.inspect)fightAudio.start();$('audioStatus').textContent=fightAudio.errors.length?'Audio unavailable: '+fightAudio.errors.join(', '):'Music stays below effects · heavy hits duck the soundtrack';syncPause();canvas.focus({preventScroll:true})}
function pauseTest(){runToken++;starting=false;paused=true;keys.clear();gestures.reset();fightAudio.pause();syncPause()}
function stopTest(){pauseTest();fightAudio.pause(true);started=false;changeSpeed(1.3);gestures.reset();lab.reset();particles=[];rings=[];popups=[];$('sequence').value='free';lab.message='TEST STOPPED · Play to begin wave one';draw()}
function togglePlay(){if(starting||!paused)pauseTest();else startTest()}
function reset(){pauseTest();fightAudio.pause(true);started=false;changeSpeed(1.3);gestures.reset();lab.reset();keys.clear();particles=[];rings=[];popups=[];shake=0;$('sequence').value='free';syncPause();canvas.focus({preventScroll:true})}
function trigger(a){if(!ready||starting)return;if(paused)return;if(lab.inspect){pauseTest();lab.inspect=null;$('sequence').value='free';return}lab.trigger(a);$('sequence').value='free';canvas.focus({preventScroll:true})}

function scan(){const on=$('stage').classList.toggle('scan');$('scan').textContent='Scanlines · '+(on?'on':'off');$('scan').classList.toggle('active',on);$('scan').setAttribute('aria-pressed',on)}
function changeSpeed(v){speed=v;$('speed').value=v*100;$('speedValue').textContent=v.toFixed(2)+'×'}
function step(){pauseTest();update(1/12);draw()}
document.addEventListener('keydown',e=>{if(e.target.matches('input,select')||e.ctrlKey||e.metaKey||e.altKey)return;if(!['KeyW','KeyA','KeyS','KeyD','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','ShiftLeft','ShiftRight','Space','KeyJ','KeyK','KeyL','KeyP','KeyR','KeyT','KeyC','Period'].includes(e.code))return;e.preventDefault();keys.add(e.code);if(e.repeat)return;const direction=['ArrowLeft','KeyA'].includes(e.code)?-1:['ArrowRight','KeyD'].includes(e.code)?1:0;if(direction&&!paused&&!lab.inspect&&gestures.direction(direction,performance.now()))lab.dash(direction);const a={KeyJ:'punch',KeyK:'kick',KeyL:'special',Space:'jump'}[e.code];if(a)trigger(['punch','kick'].includes(a)?gestures.attack(a,performance.now()):a);else if(e.code==='KeyP')togglePlay();else if(e.code==='KeyR')reset();else if(e.code==='KeyT')changeSpeed(speed===.25?1.3:.25);else if(e.code==='KeyC')scan();else if(e.code==='Period')step();else if(lab.inspect){pauseTest();lab.inspect=null;lab.player.flight=null;lab.set(lab.player,'idle');lab.set(lab.enemy,'idle');$('sequence').value='free'}});
document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();gestures.reset()});document.addEventListener('visibilitychange',()=>keys.clear());
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>trigger(['punch','kick'].includes(b.dataset.move)?gestures.attack(b.dataset.move,performance.now()):b.dataset.move));document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);lab.inspect=null;const dir=b.dataset.dir==='ArrowLeft'?-1:b.dataset.dir==='ArrowRight'?1:0;if(dir&&!paused&&gestures.direction(dir,performance.now()))lab.dash(dir);keys.add(b.dataset.dir)};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(b.dataset.dir)});
$('fighter').onchange=e=>{pauseTest();fightAudio.pause(true);lab.selectCharacter(e.target.value);reset();syncCharacter();draw()};
function syncCharacter(){const em=lab.character==='em',big=lab.character==='bully',fast=lab.character==='change';$('playerName').textContent=fast?'DJ CHANGE':big?'DJ BULLY':em?'DJ EM':'DJ PROMIS';$('playerHealth').setAttribute('aria-label',lab.playerName+' health');$('fighterDescription').textContent=fast?'DJ Change · quick punches, Rewind Kicks, turning backfist and Tempo Burst.':big?'DJ Bully · heavy fists, hammer blow, shoulder charge and grab-and-slam special.':em?'DJ Em · fast kicks, rising knee and forward electrical Synaptic Kick.':'DJ Promis · alternating fists, elbow, shoulder dash and radial shockwave.';document.querySelector('[data-move="elbow"]').textContent=fast?'Backfist · J + K':big?'Hammer blow · J + K':em?'Rising knee · J + K':'Elbow · J + K';document.querySelector('[data-move="special"] b').textContent=fast?'Tempo Burst':big?'Bass-Slam Drop':em?'Synaptic Kick':'Shockwave';document.querySelector('[data-move="special"] small').textContent=fast?'Rush, rapid strikes, final thrust':big?'Grab, lift and ground burst':em?'Forward electrical burst':'Sub-woofer slam';document.querySelector('[data-move="kick"] b').textContent=fast?'Rewind Kick':big?'Heavy boot':em?'Kick combo':'High kick';document.querySelector('[data-move="kick"] small').textContent=fast?'Tap K repeatedly to chain':big?'Heavy front kick':em?'Tap K twice: front → side':'Wind-up → snap';$('sequence').querySelector('[value="kick"]').textContent=fast?'Rewind Kick':big?'Heavy boot':em?'Kick combo':'High kick';canvas.setAttribute('aria-label',lab.playerName+' character test. Arrow keys or WASD move. J punch, K kick, L special, Space jump.');$('sequence').querySelector('[value="elbow"]').textContent=fast?'Turning backfist':big?'Hammer blow':em?'Rising knee':'Elbow';$('sequence').querySelector('[value="dash"]').textContent=fast?'Dash thrust':big?'Shoulder charge':em?'Advancing kick':'Dash';$('sequence').querySelector('[value="special"]').textContent=fast?'Tempo Burst':big?'Bass-Slam Drop':em?'Synaptic Kick':'Shockwave';}
syncCharacter();$('pause').onclick=togglePlay;$('stop').onclick=stopTest;$('step').onclick=step;$('reset').onclick=reset;$('scan').onclick=scan;$('flip').onclick=()=>lab.player.face*=-1;$('speed').oninput=e=>changeSpeed(Number(e.target.value)/100);
$('sequence').onchange=e=>{pauseTest();keys.clear();const a=e.target.value;if(a==='free'){lab.inspect=null;lab.player.flight=null;lab.set(lab.player,'idle');lab.set(lab.enemy,'idle')}else{const enemy=a.startsWith('enemy-'),action=enemy?a.slice(6):a;lab.player.flight=null;lab.inspect={actor:enemy?'enemy':'player'};lab.set(enemy?lab.enemy:lab.player,action)}paused=a==='free';syncPause()};
$('sound').onclick=()=>{fightAudio.mute(fightAudio.enabled);$('sound').textContent=fightAudio.enabled?'Audio · on':'Audio · muted';$('sound').classList.toggle('active',fightAudio.enabled);$('sound').setAttribute('aria-pressed',fightAudio.enabled)};function mix(){const fx=Number($('fxVolume').value)/100,m=Number($('musicVolume').value)/100;fightAudio.volumes(fx,m);$('fxValue').textContent=Math.round(fx*100)+'%';$('musicValue').textContent=Math.round(m*100)+'%'}$('fxVolume').oninput=mix;$('musicVolume').oninput=mix;$('fullscreen').onclick=async()=>{if(document.fullscreenElement)await document.exitFullscreen();else try{await $('stage').requestFullscreen()}catch{}};
$('enemyMode').onchange=e=>{lab.enemyMode=e.target.value;for(const e of lab.enemies){if(['phone','case','walk'].includes(e.action))lab.set(e,'idle');e.cooldown=.5}};$('god').onchange=e=>lab.god=e.target.checked;$('boxes').onchange=e=>showBoxes=e.target.checked;
document.querySelectorAll('[data-setting]').forEach(el=>{el.oninput=()=>{lab.settings[el.dataset.setting]=Number(el.value);$('value-'+el.dataset.setting).textContent=Number(el.value).toFixed(el.step.includes('.')?2:0)}});
$('defaults').onclick=()=>{Object.assign(lab.settings,DEFAULTS);document.querySelectorAll('[data-setting]').forEach(el=>{el.value=lab.settings[el.dataset.setting];el.oninput()})};
function loop(t){const dt=Math.min((t-last)/1000,.05);last=t;if(ready){if(!paused){update(dt*speed);if(lab.over)pauseTest()}draw()}requestAnimationFrame(loop)}
window.__promis={lab,get state(){return {ready,paused,speed,player:{...lab.player},enemy:{...lab.enemy},wave:lab.wave,enemies:lab.enemies.map(e=>({...e})),audio:{running:fightAudio.running,decoded:Object.keys(fightAudio.buffers).length,errors:fightAudio.errors},frames:sprites.length,enemyFrames:enemySprites.length}},reset,trigger};changeSpeed(1.3);syncPause();requestAnimationFrame(loop);
