$('stage').appendChild($('mcBox'));
const refinedSprites=[];let refinedReady=false;
class HeistSequence{
 constructor(fighter){this.kind='heist';this.fighter=fighter;this.time=0;this.finished=false;this.events=[];this.fired=new Set()}
 get phase(){return this.time<2?'entrance':this.time<4.5?'theft':this.time<10.8?'taunt':'escape'}
 update(dt){this.time=Math.min(16.2,this.time+Math.max(0,dt));for(const[t,event]of [[2,'search'],[3.5,'found'],[4.5,'taunt'],[8.9,'laugh'],[10.8,'escape'],[11.8,'hype']])if(this.time>=t&&!this.fired.has(event)){this.fired.add(event);this.events.push(event)}this.finished=this.time>=16.2}
 skip(){this.finished=true;this.time=16.2;this.events=[]}
}
function startHeist(){opening=new HeistSequence(lab.character);keys.clear();gestures.reset();entryScene=true;lab.events=[];fightAudio.introMix(1);$('stage').classList.add('intro');$('skipIntro').hidden=false;syncPause()}
function tickHeist(dt){const before=opening.time;opening.update(dt);if(opening.time<2&&Math.floor(before*3.4)!==Math.floor(opening.time*3.4))fightAudio.play('player-step',{gain:.35,x:100});for(const e of opening.events.splice(0)){const name={search:'record-search',found:'record-found',taunt:'corporate-voice',laugh:'corporate-laugh',escape:'escape-step',hype:'mc-voice'}[e];fightAudio.play(name,{gain:e==='taunt'||e==='hype'?1.15:.7,x:e==='hype'?480:705});}if(opening.finished)finishOpening()}
function setMC(hype,caption){$('mcCaption').textContent=caption;$('mcBox').classList.toggle('hype',hype);const c=$('mcPortrait'),g=c.getContext('2d'),s=heistSprites[hype?1:0];if(!s)return;g.clearRect(0,0,c.width,c.height);g.imageSmoothingEnabled=false;const sw=s.width,sh=Math.min(s.height,sw*1.05);const bounce=hype?Math.round(Math.sin((opening?opening.time:lab.clock)*15)*2):0;g.drawImage(s,0,0,sw,sh,0,bounce,c.width,c.height)}
function drawShopLife(t){ctx.save();
// Cabinet sits against the far-left wall, leaving the combat lane clear.
drawCabinet(t);
for(const x of [622,730]){ctx.fillStyle='#10151d';ctx.beginPath();ctx.ellipse(x,136,14,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d6b461';ctx.fillRect(x-2,135,4,2);ctx.fillStyle='#899393';ctx.fillRect(x+Math.cos(t*5)*10,135+Math.sin(t*5)*2,2,1)}
if(Math.sin(t*9)> .97||Math.sin(t*2.7)>.995){ctx.fillStyle='#0b161b77';ctx.fillRect(370,6,154,31)}
for(const [x,y,w,h]of [[150,44,29,43],[828,50,29,43]]){ctx.save();ctx.translate(x,y);ctx.transform(1,0,Math.sin(t*2+x)*.015,1,0,0);ctx.drawImage(shopCanvas,x/960*shopCanvas.width,y/470*shopCanvas.height,w/960*shopCanvas.width,h/470*shopCanvas.height,0,0,w,h);ctx.restore()}
ctx.fillStyle='#f4dfab';for(let i=0;i<24;i++){ctx.globalAlpha=.1+(i%4)*.04;ctx.fillRect(20+(i*31+t*(4+i%3))%300,80+(i*23+t*7)%245,2,2)}ctx.restore()}
function storySuit(index,x,y,scale=.78,bob=0){const s=heistSprites[index];if(!s)return;const h=226*scale,w=s.width/s.height*h;ctx.drawImage(s,x-w/2,y-h+bob,w,h)}
function record(x,y,gold=false){ctx.save();ctx.translate(x,y);if(gold){ctx.shadowColor='#ffe287';ctx.shadowBlur=16}ctx.fillStyle='#101824';ctx.beginPath();ctx.ellipse(0,0,15,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=gold?'#fff7d9':'#bd885d';ctx.beginPath();ctx.ellipse(0,0,5,3,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawHeist(){$('mcBox').querySelector('.score').style.visibility='hidden';const t=opening.time;ctx.setTransform(canvas.width/960,0,0,canvas.height/470,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(shopCanvas,0,0,960,470);drawShopLife(t);drawEntryScene();
introHero(opening.fighter,t<2?'walk':'ready',-65+235*Math.min(1,t/2),375,.85,1,0,t);
const crate=refinedSprites[5];if(crate){const w=100,h=w*crate.height/crate.width;ctx.drawImage(crate,619,326-h,w,h)}
if(t<3.5)storySuit(2,702,375,1.02,t<2?0:Math.sin(t*16)*2);else if(t<4.5)storySuit(3,705,375,1.02);else if(t<10.8)storySuit(4,705,375,1.02,t>=8.9?Math.sin(t*23)*1.6:0);else if(t<12.8){const u=(t-10.8)/2,frame=refinedSprites[Math.floor((t-10.8)*10)%5];if(frame){const h=231,w=frame.width/frame.height*h;ctx.drawImage(frame,705+390*u-w/2,375-h,w,h)}}
if(t>=10.8)for(let i=0;i<4;i++)if(t>10.9+i*.24)record(741+i*46,361+i%2*10);if(t>=4.5&&t<10.8){ctx.fillStyle='#fff2ca';ctx.strokeStyle='#182028';ctx.lineWidth=3;ctx.fillRect(386,52,537,84);ctx.strokeRect(386,52,537,84);ctx.fillStyle='#182028';ctx.font='bold 19px monospace';ctx.textAlign='center';ctx.fillText('CORPORATE PROPERTY NOW, SUNSHINE!',654,85);ctx.fillText('MAINSTREAM ONLY!',654,113);ctx.fillStyle='#fff2ca';ctx.beginPath();ctx.moveTo(708,136);ctx.lineTo(728,154);ctx.lineTo(736,136);ctx.fill()}
ctx.fillStyle='#0e1720e8';ctx.fillRect(0,437,960,33);ctx.fillStyle='#edd59a';ctx.font='bold 15px monospace';ctx.textAlign='left';ctx.fillText('THE DUBPLATE HEIST',18,458);ctx.textAlign='right';ctx.fillText('SPACE / ENTER · SKIP',941,458);
if(t>12.8)arcadeText('GET READY!',480,213,40);$('fightMessage').textContent='THE DUBPLATE HEIST · '+opening.phase.toUpperCase();setMC(t>=11.8,t>=11.8?"YES YES YES! Don't let him take the signal! MASSIVE, ATTACK!":'MC QC · THE VOICE OF THE UNDERGROUND');}
function drawFightCue(){$('scoreValue').textContent=String(lab.hits.player*100+lab.kills*500).padStart(6,'0');$('mcBox').querySelector('.score').style.visibility='visible';if(entryScene&&lab.clock<1.5)arcadeText('FIGHT!',480,190,65,'#ffe45f');drawMC()}
function loadHeist(){const image=new Image();image.onload=()=>{const sheet=document.createElement('canvas');sheet.width=image.width;sheet.height=image.height;const g=sheet.getContext('2d');g.drawImage(image,0,0);const im=g.getImageData(0,0,sheet.width,sheet.height),d=im.data;for(let p=0;p<d.length;p+=4)if(d[p]>110&&d[p+2]>110&&d[p]>d[p+1]*1.45&&d[p+2]>d[p+1]*1.45)d[p+3]=0;g.putImageData(im,0,0);for(let i=0;i<6;i++){const x0=Math.floor(i%3*sheet.width/3),x1=Math.floor((i%3+1)*sheet.width/3),y0=Math.floor(Math.floor(i/3)*sheet.height/2),y1=Math.floor((Math.floor(i/3)+1)*sheet.height/2);let l=x1,r=x0,top=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*sheet.width+x)*4+3]>150){l=Math.min(l,x);r=Math.max(r,x);top=Math.min(top,y);b=Math.max(b,y)}const c=document.createElement('canvas');c.width=r-l+1;c.height=b-top+1;c.getContext('2d').drawImage(sheet,l,top,c.width,c.height,0,0,c.width,c.height);heistSprites.push(c)}heistReady=true;setMC(false,'MC QC · THE VOICE OF THE UNDERGROUND');checkReady()};image.onerror=()=>{$('loading').textContent='Could not load heist artwork'};image.src='data:image/png;base64,HEIST_DATA'}loadHeist();

function loadRefined(){const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height).data;for(let i=0;i<6;i++){const x0=i%3*c.width/3,y0=Math.floor(i/3)*c.height/2,x1=x0+c.width/3,y1=y0+c.height/2;let l=x1,r=x0,top=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*c.width+x)*4+3]>150){l=Math.min(l,x);r=Math.max(r,x);top=Math.min(top,y);b=Math.max(b,y)}const f=document.createElement('canvas');f.width=r-l+1;f.height=b-top+1;f.getContext('2d').drawImage(c,l,top,f.width,f.height,0,0,f.width,f.height);refinedSprites.push(f)}refinedReady=true;checkReady()};im.src='data:image/png;base64,REFINED_DATA'}loadRefined();

let enemyHudAt=null;
function syncSceneHUD(){const hud=$('stage').querySelector('.combat-hud'),panels=[...hud.children],heist=opening?.kind==='heist';let playerAlpha=1,enemyAlpha=1;if(opening){enemyHudAt=null;playerAlpha=heist?Math.max(0,Math.min(1,(opening.time-.4)/.5)):0;enemyAlpha=0;if(heist){$('playerHP').textContent=lab.player.hp+' / 100';$('playerHealth').value=lab.player.hp;$('action').textContent=opening.time<2?'WALK':'READY';$('weaponInfo').textContent='UNARMED';$('specialPower').value=lab.charge;$('specialText').textContent='RARE VINYL '+lab.charge+' / '+lab.settings.recordsNeeded}}else if(entryScene){const visible=lab.enemies.some(e=>e.hp>0&&e.x>0&&e.x<960);if(enemyHudAt===null&&visible)enemyHudAt=lab.clock;enemyAlpha=enemyHudAt===null?0:Math.min(1,Math.max(0,(lab.clock-enemyHudAt)/.65))}else enemyHudAt=null;panels.forEach(p=>{const alpha=p.classList.contains('enemy-hud')?enemyAlpha:playerAlpha;p.style.opacity=alpha;p.style.visibility=alpha===0?'hidden':'visible'})}
