const campaign=new LevelCampaign(lab);lab.campaignDirector=campaign;
let levelArtReady=false;const levelArt={},levelCast=[];let worldShop=null,storyCaption='',storyUntil=0,storyMood='CALL TO ARMS',sceneCues=new Set();
function loadLevelArt(){let count=0;const done=()=>{if(++count===3){levelArtReady=true;checkReady()}};for(const [key,token]of [['zones','level-zones.png'],['finale','level-finale-period.png'],['cast','level-cast-key.png']]){const im=new Image();im.onload=()=>{levelArt[key]=im;if(key==='cast'){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const pixels=g.getImageData(0,0,c.width,c.height),d=pixels.data;for(let k=0;k<d.length;k+=4)if(d[k]>110&&d[k+2]>110&&d[k+1]<90&&d[k]>d[k+1]*1.8&&d[k+2]>d[k+1]*1.8)d[k+3]=0;g.putImageData(pixels,0,0);for(let i=0;i<6;i++){const x0=Math.floor(i%3*c.width/3),x1=Math.floor((i%3+1)*c.width/3),y0=Math.floor(Math.floor(i/3)*c.height/2),y1=Math.floor((Math.floor(i/3)+1)*c.height/2);let l=x1,r=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*c.width+x)*4+3]>128){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const f=document.createElement('canvas');f.width=r-l+1;f.height=b-t+1;f.getContext('2d').drawImage(c,l,t,f.width,f.height,0,0,f.width,f.height);levelCast.push(f)}}done()};im.onerror=()=>{$('loading').textContent='Level artwork could not load. Reload to retry.'};im.src=token}}
function panel(g,im,row,x,w,split=.65){const h=im.height/2,top=h*split;g.drawImage(im,0,row*h,im.width,top,x,0,w,270);g.drawImage(im,0,row*h+top,im.width,h-top,x,270,w,200)}
function prepareWorld(){if(worldShop)return;worldShop=document.createElement('canvas');worldShop.width=3860;worldShop.height=470;const g=worldShop.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(shopCanvas,0,0,960,470);panel(g,levelArt.zones,0,960,1450,.75);panel(g,levelArt.zones,1,2410,1450,.55);
 // Blend floor joins; the stockroom wall conceals the architecture seam.
 for(const x of [960]){const patch=document.createElement('canvas');patch.width=64;patch.height=470;const q=patch.getContext('2d');q.drawImage(worldShop,x,0,64,470,0,0,64,470);q.globalCompositeOperation='destination-in';const fade=q.createLinearGradient(0,0,64,0);fade.addColorStop(0,'transparent');fade.addColorStop(1,'white');q.fillStyle=fade;q.fillRect(0,0,64,470);g.drawImage(worldShop,x-64,0,64,470,x,0,64,470);g.drawImage(patch,x,0)}
 const floorPatch=document.createElement('canvas');floorPatch.width=100;floorPatch.height=200;const q=floorPatch.getContext('2d');q.drawImage(worldShop,2410,270,100,200,0,0,100,200);q.globalCompositeOperation='destination-in';const fade=q.createLinearGradient(0,0,100,0);fade.addColorStop(0,'transparent');fade.addColorStop(1,'white');q.fillStyle=fade;q.fillRect(0,0,100,200);g.drawImage(worldShop,2310,270,100,200,2410,270,100,200);g.drawImage(floorPatch,2410,270);
}
function levelSay(text,mood='DYNAMIC HYPE',duration=5){storyCaption=text;storyUntil=campaign.elapsed+duration;storyMood=mood;mcDirector.pending=[];mcDirector.next=mcDirector.time+duration;}
function levelCue(id,time,clip,gain=.75){if(campaign.time>=time&&!sceneCues.has(id)){sceneCues.add(id);fightAudio.play(clip,{gain,x:480,heavy:['slam','burst'].includes(clip)})}}
function levelTone(hz){if(!fightAudio.ctx)return;if(!fightAudio.levelFilter){const f=fightAudio.ctx.createBiquadFilter();f.type='lowpass';f.Q.value=.35;fightAudio.musicGain.disconnect();fightAudio.musicGain.connect(f);f.connect(fightAudio.master);fightAudio.levelFilter=f}fightAudio.levelFilter.frequency.setTargetAtTime(hz,fightAudio.ctx.currentTime,.4)}
function consumeLevelEvents(){for(const e of campaign.events.splice(0)){
 if(e.type==='state'){sceneCues.clear();keys.clear();gestures.reset();lab.queue=null;particles=[];popups=[];rings=[];if(lab.controlsLocked){fightAudio.stopCinematic();mcDirector.reset(4)}if(e.state==='stairs')levelSay('Hold tight, massive. Take the stairs — the signal is coming from underground!','BOSS WARNING',8);if(e.state==='bossIntro')levelSay('Boss alert! Reginald the Gatekeeper is in the dance!','BOSS ALERT',10);if(e.state==='handoff')levelSay("Red alert! They're trying to silence the broadcast! We need that signal live!",'BOSS WARNING',12);if(e.state==='transit'){fightAudio.introMix(.72);levelTone(800)}if(e.state==='arrival'){fightAudio.introMix(1);levelTone(17000)}if(e.state==='bossIntro')levelTone(2800);}
 if(e.type==='zone'){levelSay(['Keep the signal alive! Clear the front counter!','Into the aisles. Keep moving, massive!','Clear the stockroom! Watch the flanking crew!','The Gatekeeper is protecting the stolen music.'][e.index],e.index===3?'BOSS ALERT':'CALL TO ARMS',5)}
 if(e.type==='spawn'&&e.tier==='green')levelSay('Watch the heavyweights! Heavy grappling incoming — step back!','DYNAMIC HYPE',5);
 if(e.type==='spawn'&&e.tier==='black')levelSay('Black jacket! Give that ground pound some space!','BOSS WARNING',5);
 if(e.type==='clear'){fightAudio.play('record-found',{gain:.5});levelSay('Straight into the next. Follow the signal!','CALL TO ARMS',4)}
 if(e.type==='phase2'){levelSay('Gold jacket on the flank! The Gatekeeper is speeding up!','BOSS ALERT',6);fightAudio.play('charge',{gain:.6})}
 if(e.type==='key')levelSay('The key! Pick it up and free the distributor!','CALL TO ARMS',6);
 if(e.type==='rescue'){fightAudio.play('record-found',{gain:.7});levelSay('Selecta Dub Dean! The underground has its distributor back!','VICTORY',20)}
 if(e.type==='ambush')levelSay('Company on the floor! Watch both sides!','CALL TO ARMS',4);
 if(e.type==='gate')levelSay('Stockroom ahead. Smash that door!','CALL TO ARMS',5);
 if(e.type==='gateHit'){fightAudio.play(e.broken?'intro-breach':'kick-hit',{gain:.9});shake=e.broken?7:3;}
 if(e.type==='cageKey'){fightAudio.play('record-found',{gain:.65});levelSay('Key secured. Walk up to Dean’s cage!','CALL TO ARMS',8);}
 if(e.type==='state'&&e.state==='boarding')levelSay('All aboard! Next stop: Concrete Jungle.','VICTORY',10);
 if(e.type==='state'&&e.state==='transit')levelSay('Keep the signal live. The tower is up ahead.','CALL TO ARMS',10);
 if(e.type==='rank')fightAudio.play('record-found',{gain:.6});
 } }
const standardInput=input;input=function(){return campaign.active&&lab.controlsLocked?{dx:0,dy:0,run:false}:standardInput()};
const standardUpdate=update;update=function(dt){if(!campaign.active)return standardUpdate(dt);const real=dt/speed;consumeLevelEvents();if(['entry','combat','clear','travel','travelFight','gate','gateOpen','boss','key','unlock'].includes(campaign.state)){standardUpdate(dt)}campaign.update(real);consumeLevelEvents();if(campaign.state==='stairs')levelCue('stairs',1.4,'escape-step',.4);if(campaign.state==='doorExit')levelCue('through-door',.2,'player-step',.35);if(campaign.state==='bossIntro'){levelCue('threat',3,'corporate-laugh');levelCue('boss',6,'charge')}
 if(campaign.state==='rescue'){levelCue('open',2,'intro-door');levelCue('found',3.5,'record-found');levelCue('deck',6.5,'record-search');levelCue('rewind-voice',9.8,'mc-qc-rewind',1);levelCue('rewind',10,'burst',1);levelCue('slam',10,'slam',1)}
 if(campaign.state==='boarding'){levelCue('door-open',1.2,'intro-door',.6);levelCue('door-close',4,'intro-door',.7);levelCue('departure',4.3,'intro-engine',.9)}if(campaign.state==='tally'){levelCue('rank',4,'slam',.75);levelCue('rank-voice',4.2,campaign.rank==='S'?'mc-qc-absolute-pressure':campaign.rank==='A'?'mc-qc-heavy-business':'mc-qc-underground-holds-strong',1)}if(campaign.state==='transit')levelCue('engine',.1,'intro-engine',.55);if(campaign.state==='arrival')levelCue('skid',4,'intro-skid',.8);
};
const standardCollect=collectEvents;collectEvents=function(){if(campaign.active){for(const e of lab.events){campaign.record(e);if(e.weapon?.startsWith('boss')){if(e.type==='swing'&&e.weapon!=='bossJab'){rings.push({x:e.x,y:e.y,age:0,gold:true,radius:MOVES[e.weapon].reach*lab.settings.reach});shake=9;fightAudio.play('slam',{gain:.9,heavy:true})}e.weapon=e.weapon==='bossJab'?'phone':'case'}if(typeof e.x==='number')e.audioX=e.x-campaign.camera}}
 standardCollect()};
// Audio panning follows the viewport while hit effects retain world coordinates.
const campaignAudio=FightAudio.prototype.event;FightAudio.prototype.event=function(e){return campaignAudio.call(this,e.audioX===undefined?e:{...e,x:e.audioX})};
const standardFinish=finishOpening;finishOpening=function(){const isHeist=opening?.kind==='heist';standardFinish();if(isHeist){campaign.start();consumeLevelEvents()}};
const standardCancel=cancelOpening;cancelOpening=function(){const wasActive=campaign.active;campaign.cancel();levelTone(17000);if(wasActive)lab.reset();standardCancel();$('campaignTools').hidden=true};
const standardActor=drawActor;drawActor=function(a){if(a.kind==='boss'){drawReginald(a);return}standardActor(a)};
function castSprite(i,x,y,scale=1,face=1,angle=0){const s=levelCast[i];if(!s)return;ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.rotate(angle);ctx.drawImage(s,-s.width*scale/2,-s.height*scale,s.width*scale,s.height*scale);ctx.restore()}
function drawReginald(a){const scale=242/levelCast[0].height;let pose=0;const m=lab.moveData(a);if(m&&a.action!=='bossJab')pose=a.time<m.start?1:2;ctx.save();if(a.invuln>0)ctx.filter='brightness(1.35)';const down=['down','defeated'].includes(a.action);if(down){ctx.translate(a.x-70,a.y-5);ctx.rotate(-Math.PI/2);castSprite(0,0,0,scale,1)}else castSprite(pose,a.x,a.y-lab.height(a)+(a.action==='walk'?Math.sin(a.time*14)*2:0),scale,a.face,a.action==='hurt'?-.08:0);ctx.restore();if(m&&a.time<m.start){const r=m.reach,alpha=.18+.14*Math.sin(a.time*22);ctx.fillStyle='rgba(255,97,58,'+alpha+')';ctx.beginPath();ctx.ellipse(a.x,a.y,r,m.depth,0,0,Math.PI*2);ctx.fill();arcadeText(a.action==='bossBurst'?'CLOSED! · JUMP / EVADE':'WATCH THE SIGN!',a.x,a.y-285,14,'#ffbc68')}}
function drawLevelBackground(){ctx.imageSmoothingEnabled=false;if(campaign.zone===2){drawStockroomWorld();return}if(campaign.zone===3){panel(ctx,levelArt.finale,0,0,960,.67);const t=campaign.time+lab.clock,swing=Math.sin(t*1.2)*18;ctx.save();ctx.globalCompositeOperation='screen';const light=ctx.createRadialGradient(480+swing,200,10,480+swing,200,290);light.addColorStop(0,'#d993301e');light.addColorStop(1,'#e9b75b00');ctx.fillStyle=light;ctx.fillRect(0,0,960,470);ctx.strokeStyle='#30271b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(480,0);ctx.lineTo(480+swing,43);ctx.stroke();ctx.fillStyle='#ffe6a7';ctx.beginPath();ctx.arc(480+swing,45,4,0,Math.PI*2);ctx.fill();ctx.restore()}else{prepareWorld();ctx.drawImage(worldShop,campaign.camera,0,960,470,0,0,960,470);if(campaign.camera<960){ctx.save();ctx.translate(-campaign.camera,0);drawShopLife(lab.clock);drawEntryScene();ctx.restore()}drawShopPartition();if(campaign.zone===2)drawStairwell(false)}}
function wrapCaption(text,x,y,width=840,size=17){ctx.save();ctx.font='bold '+size+'px monospace';const words=text.split(' '),lines=[];let line='';for(const w of words){if(ctx.measureText(line+w).width>width-28){lines.push(line.trim());line=''}line+=w+' '}if(line)lines.push(line.trim());const h=lines.length*(size+7)+20;ctx.fillStyle='#081722ef';ctx.fillRect(x-width/2,y,width,h);ctx.strokeStyle='#5a969e';ctx.lineWidth=1;ctx.strokeRect(x-width/2,y,width,h);ctx.textAlign='center';ctx.fillStyle='#fff1c6';lines.forEach((line,i)=>ctx.fillText(line,x,y+size+9+i*(size+7)));ctx.restore()}
function drawKey(){if(!campaign.key)return;const k=campaign.key;ctx.save();ctx.translate(k.x,k.y);ctx.shadowColor='#ffdb56';ctx.shadowBlur=15;ctx.strokeStyle='#ffdf76';ctx.lineWidth=5;ctx.beginPath();ctx.arc(-5,-14,9,0,Math.PI*2);ctx.moveTo(4,-14);ctx.lineTo(30,-14);ctx.lineTo(30,-5);ctx.moveTo(22,-14);ctx.lineTo(22,-8);ctx.stroke();ctx.restore();arcadeText('J · PICK UP KEY',k.x,k.y+22,12)}
function levelHUD(){syncSceneHUD();const p=lab.player,boss=lab.enemies.find(e=>e.kind==='boss'&&e.hp>0),live=lab.enemies.filter(e=>e.hp>0);$('campaignTools').hidden=false;$('checkpoint').disabled=!campaign.checkpoint;$('campaignSkip').hidden=!lab.controlsLocked||campaign.state==='entry'||campaign.state==='complete';$('campaignSkip').textContent=campaign.state==='tally'?'Continue to Level 2':'Skip scene';$('playerHP').textContent=p.hp+' / 100';$('playerHealth').value=p.hp;$('specialPower').max=lab.settings.recordsNeeded;$('specialPower').value=lab.charge;$('specialText').textContent=lab.charge>=lab.settings.recordsNeeded?'L · SPECIAL READY':'RARE VINYL '+lab.charge+' / '+lab.settings.recordsNeeded;$('action').textContent=lab.controlsLocked?'STORY':p.action.toUpperCase();$('weaponInfo').textContent=p.held?(p.held.gold?'GOLD BATON':'BATON')+' · '+p.held.hits+' HITS':'UNARMED';$('enemyName').textContent=boss?'REGINALD “THE GATEKEEPER”':LEVEL_ZONES[campaign.zone].name;$('enemyHealth').max=boss?boss.maxHP:live.reduce((n,e)=>n+e.maxHP,0)||1;$('enemyHealth').value=boss?boss.hp:live.reduce((n,e)=>n+e.hp,0);$('enemyHealth').setAttribute('aria-label',boss?'Reginald health':'Encounter health');$('enemyHP').textContent=boss?boss.hp+' / '+boss.maxHP:live.length+' OPPONENT'+(live.length===1?'':'S');$('enemyAction').textContent=boss?(boss.bossPhase===2?'PHASE 2 · GOLD REINFORCEMENT':'READ THE WIND-UP'):'ZONE '+LEVEL_ZONES[campaign.zone].number+' / 3';const eh=$('enemyName').closest('.enemy-hud');eh.style.visibility=live.length&&!lab.controlsLocked?'visible':'hidden';const cinematic=['rescue','handoff','tally','boarding','transit','arrival','complete'].includes(campaign.state);$('stage').querySelector('.combat-hud').style.visibility=cinematic?'hidden':'visible';for(const child of $('stage').querySelector('.combat-hud').children)if(cinematic)child.style.visibility='hidden';$('hits').textContent='ZONE '+LEVEL_ZONES[campaign.zone].number+' / 3 · KOs '+campaign.stats.defeats+' · COMBO '+campaign.stats.combo;$('status').textContent=lab.over?'DOWN · N TO RETRY':paused?'PAUSED':campaign.state.toUpperCase();$('scoreValue').textContent=String(campaign.stats.defeats*500+lab.hits.player*100).padStart(6,'0');$('mcBox').querySelector('.score').style.visibility='visible';$('fightMessage').textContent=lab.over?'You went down. Retry the current checkpoint.':campaign.state==='travel'?'KEEP RIGHT · follow the signal through the shop':campaign.state==='clear'?'AREA CLEAR · walk right to continue':campaign.state==='unlock'?'Key secured. Walk up to Dean’s cage to release him.':campaign.state==='gateOpen'?'Walk right through the broken doorway.':campaign.state==='gate'?'J / K · Break through the stockroom door':campaign.state==='key'?'The Gatekeeper dropped the key. Walk over and press J.':'LEVEL 1 · '+LEVEL_ZONES[campaign.zone].name+' · '+campaign.state.toUpperCase();
 if(lab.controlsLocked||campaign.elapsed<storyUntil){setMC(true,storyCaption);$('mcBox').dataset.mood=storyMood;$('mcBox').querySelector('b').textContent='MC QC · '+storyMood}else{drawMC();$('mcBox').querySelector('b').textContent='MC QC';$('mcBox').dataset.mood='HYPE'}
}
function renderCombatLevel(){drawLevelBackground();if(campaign.zone===3)drawDeanCage(0,true);ctx.save();ctx.translate(-campaign.camera+(shake?Math.sin(lab.clock*90)*shake:0),0);drawVinyl();drawWeapons();rings.forEach(ring);[lab.player,...lab.enemies].filter(a=>a.action!=='defeated'||a.time<1.8).sort((a,b)=>a.y-b.y).forEach(drawActor);drawKey();for(const p of particles){ctx.globalAlpha=1-p.age/.3;ctx.fillStyle='#efb47a';ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;for(const p of popups){ctx.fillStyle=p.who==='enemy'?'#ffeeb4':'#ff9c86';ctx.font='bold 17px monospace';ctx.fillText('-'+p.damage,p.x,p.y-35-p.age*35)}if(showBoxes){drawBoxes(lab.player);lab.enemies.forEach(drawBoxes)}ctx.restore();if(campaign.zone===2)drawStairwell(true);if(campaign.state==='unlock')arcadeText('KEY SECURED · APPROACH CAGE →',700,370,12);if(campaign.state==='entry')arcadeText(LEVEL_ZONES[campaign.zone].name,480,168,30);if(['combat','travelFight'].includes(campaign.state)&&campaign.time<1.2)arcadeText('FIGHT!',480,205,52,'#ffe36e');if(['clear','travel'].includes(campaign.state)){arcadeText('GO! →',850,240,30,Math.sin(lab.clock*7)>0?'#ffe77d':'#eda54d');if(campaign.zone===2&&campaign.stockFinished)arcadeText('BASEMENT →',590,240,14)}if(lab.over){wrapCaption('DOWN!  N · Retry checkpoint',480,172,720,20)}}
function drawOpenedCrate(t){const im=levelArt.finale,h=im.height/2;ctx.save();ctx.filter='brightness(.38)';ctx.drawImage(im,im.width*.72,h*.28,im.width*.14,h*.16,738,193,103,75);ctx.restore();ctx.save();ctx.translate(842,181);ctx.transform(Math.max(.18,1-clamp01(t/1.2)),.12*clamp01(t/1.2),0,1,0,0);ctx.drawImage(im,im.width*.755,h*.455,im.width*.105,h*.20,-106,0,106,95);ctx.restore()}
function drawBasementStory(){if(campaign.state==='rescue'){drawRescue();return}if(campaign.state==='handoff'){drawHandoff();return}drawLevelBackground();drawDeanCage(0,true);const t=campaign.time,scale=242/levelCast[0].height,dscale=230/levelCast[5].height;introHero(lab.character,'ready',175,395,.9,1);if(campaign.state==='bossIntro'){if(t<4.5){storySuit(t<2?3:4,630,362,.95);if(t<2.8)record(630,225,true);wrapCaption(t<2.8?'The A&R Suit locks the Master Dubplate inside the crate.':'“Nobody gets past the Gatekeeper.”',480,76,760,17)}if(t>=3){if(t<5)motionSprite(Math.floor(t*6)%2,Math.min(690,1040-(t-3)*180),377,242,-1);else castSprite(0,690,377,scale,-1);arcadeText('REGINALD SMYTHE',490,122,31,'#efc971');arcadeText('THE GATEKEEPER',490,155,20)}return}
 if(campaign.state==='rescue'){
  const x=t<4?760:760-210*clamp01((t-4)/2);drawOpenedCrate(t);
  castSprite(t<5?3:t<14?4:5,x,385,dscale,1,t>=9.7&&t<10.2?-.04:0);
  
  if(t<10)for(let i=0;i<2;i++)storySuit(4,650+i*185,410,.78,Math.sin(t*8+i)*2);
  if(t>=10&&t<13){const u=(t-10)/3;ring({x:550,y:385,age:(t-10)% .7,radius:700});ctx.strokeStyle='#171613';ctx.lineWidth=2;for(let i=0;i<14;i++){const a=i*2.399;ctx.beginPath();ctx.moveTo(550,385);ctx.lineTo(550+Math.cos(a)*120,385+Math.sin(a)*35);ctx.lineTo(550+Math.cos(a+.15)*240,385+Math.sin(a+.15)*70);ctx.stroke()}arcadeText('REWIND!',480,144,62,'#8beaff');for(let i=0;i<2;i++){ctx.save();ctx.translate(650+i*185+u*650,410-u*90);ctx.rotate(u*.4);storySuit(4,0,0,.78);ctx.restore()}ctx.fillStyle='rgba(129,236,255,'+Math.max(0,.28-u)+')';ctx.fillRect(0,0,960,470)}
  if(t>=14){arcadeText('SELECTA “DUB” DEAN',480,124,30,'#ffe49b');arcadeText('LEGENDARY DISTRIBUTOR FREED!',480,157,20,'#88e6d8')}
 }else if(campaign.state==='handoff'){
  if(t<3)motionSprite(4+Math.floor(t*6)%2,550-200*clamp01(t/3),385,230,-1);else if(t<4)castSprite(5,350,385,dscale,-1);else motionSprite(6,350,385,230,1);if(t<4)record(350-130*clamp01((t-2)/2),270,true);else record(193,270,true);
  if(t>=4){wrapCaption('DEAN: “The Council is jamming the frequency! They’re taking over the Tower Block antenna!”',480,88,820,18)}
  else wrapCaption('The Master Dubplate is back in underground hands.',480,90,760,20);
 }
}
function storyCar(x,y,w=460,frame=0){const saved=opening;opening={fighter:lab.character};drawCar(frame,x,y,w,frame>=4?6:0);opening=saved}
function drawTally(){const t=campaign.time;ctx.fillStyle='#081823';ctx.fillRect(0,0,960,470);ctx.save();ctx.globalAlpha=.25;ctx.drawImage(exteriorImage,0,0,960,470);ctx.restore();arcadeText('VIBE CHECK',480,86,47,'#76e8e0');storyCar(242,400,430,4);introHero(lab.character,'idle',225,397,.79,1,-.08);ctx.fillStyle='#0a1825ec';ctx.fillRect(485,121,442,260);ctx.strokeStyle='#6bbbbb';ctx.strokeRect(485,121,442,260);const k=clamp01(t/3),s=campaign.stats;ctx.font='bold 20px monospace';ctx.fillStyle='#e8e0bb';ctx.textAlign='left';['ENFORCERS DROPPED','MAX COMBO','TIME','DUBPLATES RESCUED'].forEach((a,i)=>ctx.fillText(a,507,158+i*43));ctx.textAlign='right';[Math.floor(s.enforcers*k),Math.floor(s.maxCombo*k),Math.floor(campaign.elapsed/60)+':'+String(Math.floor(campaign.elapsed%60)).padStart(2,'0'),Math.floor(s.records*k)].forEach((a,i)=>ctx.fillText(a,904,158+i*43));if(t>=4){arcadeText(campaign.rank,711,365,67,'#ffd874');arcadeText(lab.god?'PRACTICE RUN · INFINITE HEALTH':'UNDERGROUND RATING',707,395,12);levelSay(campaign.rank==='S'?'Total devastation! Original selecta style!':campaign.rank==='A'?'Heavy business! The underground holds strong!':'Signal rescued. Keep it rolling, massive!','VICTORY',3)}arcadeText('ENTER / CONTINUE → CONCRETE JUNGLE',480,443,18);if(t<.65){const radius=1000*(1-t/.65);ctx.save();ctx.fillStyle='#04070b';ctx.beginPath();ctx.rect(0,0,960,470);ctx.arc(480,235,radius,0,Math.PI*2,true);ctx.fill('evenodd');ctx.restore()}}
function rain(t){ctx.save();ctx.strokeStyle='#9ac9dd55';ctx.lineWidth=1;for(let i=0;i<90;i++){const x=(i*97+t*180)%1020-30,y=(i*43+t*300)%500-20;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-6,y+15);ctx.stroke()}ctx.restore()}
function towerScene(t,pan=false){const im=levelArt.finale,h=im.height/2;ctx.save();if(pan){const u=t<2?clamp01(t/2):t<4?1-clamp01((t-2)/2):0;ctx.drawImage(im,im.width*.1,h,im.width*.8,h*(1-u*.32),0,0,960,470)}else ctx.drawImage(im,0,h,im.width,h,0,0,960,470);ctx.restore();rain(t);if(Math.sin(t*7)>0){ctx.fillStyle='#ff6955';ctx.shadowColor='#ff281e';ctx.shadowBlur=16;ctx.fillRect(478,30,4,4);ctx.shadowBlur=0}}
function drawTransit(){const t=campaign.time;ctx.fillStyle='#0a1626';ctx.fillRect(0,0,960,470);const im=levelArt.finale,h=im.height/2;for(let i=-1;i<3;i++)ctx.drawImage(im,0,h,im.width,h,i*960-(t*105)%960,-55,960,470);ctx.fillStyle='#09121b';ctx.fillRect(0,391,960,79);ctx.fillStyle='#9eac9c';for(let i=-1;i<10;i++)ctx.fillRect(i*160-(t*430)%160,443,70,3);storyCar(480+Math.sin(t*3)*3,418,470,0);rotatingWheels(0,480+Math.sin(t*3)*3,418,470,t*18);for(let i=-1;i<4;i++){const x=i*420-(t*290)%420;ctx.fillStyle='#18262d';ctx.fillRect(x,64,7,341);ctx.fillRect(x,61,49,6);ctx.fillStyle='#ffe6a5';ctx.fillRect(x+35,65,16,4)}rain(t);arcadeText('DESTINATION: CONCRETE JUNGLE ESTATE',480,65,24);arcadeText('LONDON / 1995',480,96,14,'#b1dce5')}
function drawArrival(){const t=campaign.time;towerScene(t,true);if(t>=3.5){storyCar(-280+660*easeOut((t-3.5)/2),421,420,t>6?5:0);if(t<5.5)rotatingWheels(0,-280+660*easeOut((t-3.5)/2),421,420,18*easeOut((t-3.5)/2));if(t>4.3&&t<6.1)smoke(225,423,t-4.3,10)}if(t>=6)introHero(lab.character,t<8?'walk':'ready',430+160*clamp01((t-6)/2),420,.78,1,0,t);if(t>=7){arcadeText('LEVEL 2',480,94,28,'#ffdc88');arcadeText('PIRATE RADIO TOWER BLOCK',480,128,29,'#8be5ed');wrapCaption('MC QC: The Euro-Pop Producer has locked down the stairwells. Fight to the roof and defend the pirate antenna!',480,157,820,17);levelSay('Listen close, massive! Fight your way to the roof. Keep the pirate signal live!','CALL TO ARMS',8)}}
const standardDraw=draw;draw=function(){if(!campaign.active){$('stage').querySelector('.combat-hud').style.visibility='visible';$('mcBox').querySelector('b').textContent='MC QC';return standardDraw()}if(!levelArtReady)return;ctx.setTransform(canvas.width/960,0,0,canvas.height/470,0,0);ctx.imageSmoothingEnabled=false;ctx.fillStyle='#08131c';ctx.fillRect(0,0,960,470);const s=campaign.state;
 if(['entry','combat','clear','travel','travelFight','gate','gateOpen','boss','key','unlock'].includes(s))renderCombatLevel();
 else if(s==='stairs')drawStairsDescent();else if(s==='doorExit')drawDoorExit();
 else if(['bossIntro','rescue','handoff'].includes(s))drawBasementStory();else if(s==='tally')drawTally();else if(s==='boarding')drawBoarding();else if(s==='transit')drawTransit();else if(s==='arrival')drawArrival();else if(s==='complete'){towerScene(12);storyCar(370,421,420,5);introHero(lab.character,'ready',590,420,.78,1);arcadeText('THE SIGNAL CONTINUES…',480,132,34,'#88e5ee');wrapCaption('LEVEL 1 COMPLETE · The crew has reached Concrete Jungle Estate. Level 2 combat is the next chapter.',480,173,800,18);arcadeText('R · REPLAY LEVEL 1',480,295,22)}
 levelHUD();if(lab.controlsLocked&&!['entry','complete','tally'].includes(s))arcadeText('ENTER / SPACE · SKIP SCENE',790,455,11,'#bbd4d3');};
function skipCampaignScene(){if(!campaign.active||campaign.time<.8)return;if(campaign.state==='tally'&&campaign.time<4){campaign.time=4;return}if(lab.controlsLocked&&campaign.state!=='entry'){fightAudio.stopCinematic();campaign.nextScene();consumeLevelEvents()}}
document.addEventListener('keydown',e=>{if(!campaign.active||e.target.matches('input,select')||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='KeyN'&&lab.over){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)$('checkpoint').click();return}if(['Enter','Space'].includes(e.code)&&lab.controlsLocked){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat&&!paused)skipCampaignScene()}},true);
$('campaignSkip').onclick=skipCampaignScene;$('checkpoint').onclick=()=>{if(!campaign.active)return;fightAudio.stopCinematic();campaign.retry();consumeLevelEvents();paused=false;started=true;fightAudio.start();syncPause();canvas.focus({preventScroll:true})};
const levelMotion=[],mcMoodSprites=[];let levelMotionReady=false,mcMoodReady=false;
function loadLevelMotion(){const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const pixels=g.getImageData(0,0,c.width,c.height),d=pixels.data,W=c.width,H=c.height;for(let k=0;k<d.length;k+=4)if(d[k]>110&&d[k+2]>110&&d[k+1]<90&&d[k]>d[k+1]*1.8&&d[k+2]>d[k+1]*1.8)d[k+3]=0;g.putImageData(pixels,0,0);
 for(let row=0;row<2;row++){const y0=row*H/2,y1=(row+1)*H/2,seen=new Uint8Array(W*H/2),parts=[];for(let y=y0;y<y1;y++)for(let x=0;x<W;x++){const k=(y-y0)*W+x;if(seen[k]||d[(y*W+x)*4+3]<128)continue;seen[k]=1;const q=[y*W+x],points=[];let l=x,r=x,t=y,b=y;while(q.length){const p=q.pop(),px=p%W,py=Math.floor(p/W);points.push(p);l=Math.min(l,px);r=Math.max(r,px);t=Math.min(t,py);b=Math.max(b,py);for(const n of [p-1,p+1,p-W,p+W]){const nx=n%W,ny=Math.floor(n/W),j=(ny-y0)*W+nx;if(nx>=0&&nx<W&&ny>=y0&&ny<y1&&Math.abs(nx-px)<=1&&!seen[j]&&d[n*4+3]>=128){seen[j]=1;q.push(n)}}}if(points.length>500)parts.push({l,r,t,b,points})}const chosen=parts.sort((a,b)=>b.points.length-a.points.length).slice(0,4).sort((a,b)=>a.l-b.l);for(const p of chosen){const f=document.createElement('canvas');f.width=p.r-p.l+1;f.height=p.b-p.t+1;const q=f.getContext('2d'),v=q.createImageData(f.width,f.height);for(const n of p.points){const k=((Math.floor(n/W)-p.t)*f.width+n%W-p.l)*4;for(let j=0;j<4;j++)v.data[k+j]=d[n*4+j]}q.putImageData(v,0,0);levelMotion.push(f)}}if(levelMotion.length!==8){$('loading').textContent='Character motion atlas could not be prepared.';return}levelMotionReady=true;checkReady()};im.src='level-cast-motion-key.png'}
function motionSprite(i,x,y,h=242,face=1){const s=levelMotion[i],reference=levelMotion[i<4?0:7];if(!s||!reference)return;const scale=h/reference.height;ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(s,-s.width*scale/2,-s.height*scale,s.width*scale,s.height*scale);ctx.restore()}
const signActor=drawReginald;drawReginald=function(a){if(['walk','bossJab','down','defeated'].includes(a.action)){const pose=a.action==='walk'?Math.floor(a.time/.18)%2:a.action==='bossJab'?2:3;motionSprite(pose,a.x,a.y-lab.height(a),242,a.face);if(a.action==='bossJab'&&a.time<lab.moveData(a).start)arcadeText('STRIKE!',a.x,a.y-263,14,'#ffbd70');return}signActor(a)};
function loadMCMoods(){const im=new Image();im.onload=()=>{for(let i=0;i<6;i++){const c=document.createElement('canvas');c.width=im.width/3;c.height=im.height/2;c.getContext('2d').drawImage(im,i%3*c.width,Math.floor(i/3)*c.height,c.width,c.height,0,0,c.width,c.height);mcMoodSprites.push(c)}mcMoodReady=true;checkReady()};im.src='mc-moods.png'}
const classicMC=setMC;setMC=function(hype,caption){classicMC(hype,caption);if(!campaign.active||!mcMoodReady)return;const mood=lab.controlsLocked||campaign.elapsed<storyUntil?storyMood:hype?'DYNAMIC HYPE':'IDLE',index={'IDLE':0,'CALL TO ARMS':1,'DYNAMIC HYPE':2,'BOSS WARNING':3,'BOSS ALERT':4,'VICTORY':5}[mood]??0,s=mcMoodSprites[index],c=$('mcPortrait'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.imageSmoothingEnabled=false;g.drawImage(s,0,0,s.width,s.height,0,0,c.width,c.height)};
loadLevelArt();loadLevelMotion();loadMCMoods();
