const fs=require('fs');let p='work/heist-runtime.js',s=fs.readFileSync(p,'utf8');const end=s.indexOf('function setMC');s=`const refinedSprites=[];let refinedReady=false;
class HeistSequence{
 constructor(fighter){this.kind='heist';this.fighter=fighter;this.time=0;this.finished=false;this.events=[];this.fired=new Set()}
 get phase(){return this.time<2?'entrance':this.time<4.5?'theft':this.time<10.8?'taunt':'escape'}
 update(dt){this.time=Math.min(16.2,this.time+Math.max(0,dt));for(const[t,event]of [[2,'search'],[3.5,'found'],[4.5,'taunt'],[8.9,'laugh'],[10.8,'escape'],[11.8,'hype']])if(this.time>=t&&!this.fired.has(event)){this.fired.add(event);this.events.push(event)}this.finished=this.time>=16.2}
 skip(){this.finished=true;this.time=16.2;this.events=[]}
}
function startHeist(){opening=new HeistSequence(lab.character);keys.clear();gestures.reset();entryScene=true;lab.events=[];fightAudio.introMix(1);$('stage').classList.add('intro');$('skipIntro').hidden=false;syncPause()}
function tickHeist(dt){const before=opening.time;opening.update(dt);if(opening.time<2&&Math.floor(before*3.4)!==Math.floor(opening.time*3.4))fightAudio.play('player-step',{gain:.35,x:100});for(const e of opening.events.splice(0)){const name={search:'record-search',found:'record-found',taunt:'corporate-voice',laugh:'corporate-laugh',escape:'escape-step',hype:'mc-voice'}[e];fightAudio.play(name,{gain:e==='taunt'||e==='hype'?1.15:.7,x:e==='hype'?480:705});}if(opening.finished)finishOpening()}
`+s.slice(end);
s=s.replace("const landing=Math.max(0,1-t/.4);introHero(opening.fighter,t<.65?'roll':'ready',170,375-landing*32,.85,1,0,t);","introHero(opening.fighter,t<2?'walk':'ready',-65+235*Math.min(1,t/2),375,.85,1,0,t);");
const a=s.indexOf("ctx.save();ctx.shadowColor='#ffd75e'");const b=s.indexOf("if(t>=7.5)",a);s=s.slice(0,a)+`const crate=refinedSprites[5];if(crate){const w=100,h=w*crate.height/crate.width;ctx.drawImage(crate,619,305-h,w,h)}
if(t<3.5)storySuit(2,702,355,.84,t<2?0:Math.sin(t*16)*2);else if(t<4.5)storySuit(3,705,355,.84);else if(t<10.8)storySuit(4,705,355,.84,t>=8.9?Math.sin(t*23)*1.6:0);else if(t<12.8){const u=(t-10.8)/2,frame=refinedSprites[Math.floor((t-10.8)*10)%5];if(frame){const h=190,w=frame.width/frame.height*h;ctx.drawImage(frame,705+390*u-w/2,355-h,w,h)}}
`+s.slice(b);
s=s.replaceAll('t>=7.5','t>=10.8').replaceAll('7.6+i*.24','10.9+i*.24').replaceAll('t>=4&&t<7.5','t>=4.5&&t<10.8').replaceAll('t>9.2','t>12.8').replaceAll('t>=9.2','t>=11.8');
s+=`\nfunction loadRefined(){const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height).data;for(let i=0;i<6;i++){const x0=i%3*c.width/3,y0=Math.floor(i/3)*c.height/2,x1=x0+c.width/3,y1=y0+c.height/2;let l=x1,r=x0,top=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*c.width+x)*4+3]>150){l=Math.min(l,x);r=Math.max(r,x);top=Math.min(top,y);b=Math.max(b,y)}const f=document.createElement('canvas');f.width=r-l+1;f.height=b-top+1;f.getContext('2d').drawImage(c,l,top,f.width,f.height,0,0,f.width,f.height);refinedSprites.push(f)}refinedReady=true;checkReady()};im.src='data:image/png;base64,REFINED_DATA'}loadRefined();\n`;
fs.writeFileSync(p,s);
p='work/combat-runtime.js';s=fs.readFileSync(p,'utf8').replace('openingAssetsReady&&heistReady','openingAssetsReady&&heistReady&&refinedReady');fs.writeFileSync(p,s);
p='work/intro-runtime.js';s=fs.readFileSync(p,'utf8').replace("lab.make('enemy',650+i*135,-1)","lab.make('enemy',-30-i*30,1)").replace('e.dropRemaining=.85+i*.15;','e.entering=true;').replace("if(cue==='engine')fightAudio.cinematicSound('engine')","if(cue==='engine')fightAudio.play('intro-engine',{gain:.8})").replace("if(cue==='brake')fightAudio.cinematicSound('skid')","if(cue==='brake')fightAudio.play('intro-skid',{gain:.85})").replace("if(cue==='door')fightAudio.play('case-hit',{gain:.9,heavy:true})","if(cue==='door')fightAudio.play('intro-door',{gain:.85})").replace("fightAudio.cinematicSound('crack');","fightAudio.play('intro-breach',{gain:.85});");fs.writeFileSync(p,s);
p='work/build-combat.cjs';s=fs.readFileSync(p,'utf8').replace("[['HEIST_DATA'","[['REFINED_DATA','heist-refined.png'],['HEIST_DATA'");const at=s.indexOf('const enemyLoader=');s=s.slice(0,at)+`html=html.replaceAll('21-second opening','27-second opening').replace('</style>','#playfield{position:relative}#mcBox{position:absolute;left:12px;bottom:32px;z-index:8;width:240px;max-width:42%;min-height:0;margin:0;padding:7px;gap:8px;border-radius:3px;pointer-events:none;background:#10252ded;font-size:10px}#mcPortrait{width:50px;height:54px;flex-shrink:0}#mcBox .score{display:none}#mcBox span{line-height:1.3;margin-top:3px}#playfield:fullscreen{display:block;padding:0}#playfield:fullscreen .stage{margin:auto;width:min(100vw,calc((100vh - 76px)*2.04))}#playfield:fullscreen .stage.intro{width:min(100vw,calc(100vh*2.04))}#playfield:fullscreen #mcBox{width:240px;bottom:32px;left:calc((100vw - min(100vw,(100vh - 76px)*2.04))/2 + 12px);margin:0}@media(max-width:650px){#mcBox{font-size:8px;bottom:24px;left:6px;padding:4px;gap:5px;width:205px}#mcPortrait{width:36px;height:40px}}</style>');\n`+s.slice(at);fs.writeFileSync(p,s);
