// Detailed raster scenery, with foreground layers for physically occluded exits.
const exitArt={};let exitArtReady=false;
const SHOP_EXIT={x:765,y:76,w:195,h:354};let stockroomWorld=null;
function loadExitArt(){let n=0;for(const [key,file]of [['door','stockroom-exit-key-v4.png'],['wall','stockroom-exit-v3.png'],['corridor','stockroom-corridor-v4.png'],['stairs','stockroom-stairs-v4.png'],['cage','dean-cage-v3.png']]){const im=new Image();im.onload=()=>{exitArt[key]=im;if(key==='door')prepareDoor(im);if(key==='cage')prepareCage(im);if(++n===5){exitArtReady=true;checkReady()}};im.onerror=()=>{$('loading').textContent='Exit scenery could not load. Reload to retry.'};im.src=file}}
function prepareDoor(im){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4)if(d.data[i]>110&&d.data[i+2]>110&&d.data[i+1]<110&&d.data[i]>d.data[i+1]*1.6&&d.data[i+2]>d.data[i+1]*1.6)d.data[i+3]=0;g.putImageData(d,0,0);exitArt.door=c;}
function drawDoorPanel(open,foreground=false){const im=exitArt.door,r=SHOP_EXIT;ctx.save();if(!foreground){ctx.beginPath();ctx.moveTo(765,0);ctx.lineTo(960,0);ctx.lineTo(960,433);ctx.lineTo(765,397);ctx.closePath();ctx.clip();ctx.fillStyle='#32251e';ctx.fillRect(765,0,195,440);for(let y=0;y<440;y+=30)ctx.drawImage(exitArt.wall,0,0,650,100,765,y,195,30)}else{ctx.beginPath();ctx.rect(r.x+r.w*.82,r.y,r.w*.18,r.h);ctx.clip()}ctx.drawImage(im,open?864:165,20,585,986,r.x,r.y,r.w,r.h);ctx.restore()}
function drawStockroomWorld(){if(!stockroomWorld){stockroomWorld=document.createElement('canvas');stockroomWorld.width=2880;stockroomWorld.height=470;const g=stockroomWorld.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(exitArt.corridor,0,0,1952,470);g.drawImage(exitArt.stairs,1920,0,960,470);const seam=document.createElement('canvas');seam.width=48;seam.height=470;const q=seam.getContext('2d');q.drawImage(exitArt.stairs,0,0,exitArt.stairs.width*.05,exitArt.stairs.height,0,0,48,470);q.globalCompositeOperation='destination-in';const f=q.createLinearGradient(0,0,48,0);f.addColorStop(0,'transparent');f.addColorStop(1,'white');q.fillStyle=f;q.fillRect(0,0,48,470);g.drawImage(exitArt.corridor,exitArt.corridor.width-60,0,60,exitArt.corridor.height,1920,0,48,470);g.drawImage(seam,1920,0);}ctx.drawImage(stockroomWorld,campaign.camera-LEVEL_ZONES[2].x,0,960,470,0,0,960,470)}
function drawShopPartition(){if(campaign.zone!==1)return;drawDoorPanel(campaign.gateHP===0);if(campaign.gateHP>0&&campaign.gateHP<3){ctx.save();ctx.strokeStyle='#19140f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(837,205);ctx.lineTo(849,243);ctx.lineTo(837,266);ctx.lineTo(846,295);ctx.stroke();ctx.restore()}if(campaign.state==='gate')arcadeText('J / K · BREAK THROUGH',834,434,12);if(campaign.state==='gateOpen')arcadeText('WALK THROUGH →',824,434,12)}
function doorExitPose(t,start={x:792,y:375}){const u=Math.max(0,Math.min(1,t/2.6));return {x:start.x+(1050-start.x)*u,y:start.y+(375-start.y)*Math.min(1,t/.8),hidden:t>=2.6}}
function drawDoorExit(){drawLevelBackground();const t=campaign.time,p=doorExitPose(t,campaign.doorStart);if(!p.hidden)introHero(lab.character,'walk',p.x,p.y,.85,1,0,t);drawDoorPanel(true,true);if(t>=2.9){ctx.fillStyle='#03070a';ctx.fillRect(0,0,960,470)}}
function drawStairwell(foreground=false){if(!foreground)return;const shift=LEVEL_ZONES[2].x+1920-campaign.camera;if(shift>960)return;ctx.save();ctx.translate(shift,0);const mask=new Path2D();mask.rect(606,290,354,180);mask.rect(610,233,350,7);for(const x of [612,723,939])mask.rect(x-4,237,8,55);ctx.clip(mask);ctx.drawImage(exitArt.stairs,0,0,960,470);ctx.restore()}
function basementDescentPose(t,start={x:580,y:320}){if(t<1.3){const u=t/1.3;return{x:start.x+(650-start.x)*u,y:start.y+(245-start.y)*u,hidden:false}}const u=Math.max(0,Math.min(1,(t-1.3)/4));return{x:650+250*u,y:245+u*320+Math.sin(u*14*Math.PI*2)*1.5,hidden:t>=5.3}}
function drawStairsDescent(){drawLevelBackground();const t=campaign.time,p=basementDescentPose(t,campaign.stairsStart);if(!p.hidden){ctx.save();ctx.beginPath();ctx.rect(0,0,960,470);ctx.clip();introHero(lab.character,'walk',p.x,p.y,.85,1,0,t);ctx.restore()}drawStairwell(true);if(t>=5.8){ctx.fillStyle='#03070a';ctx.fillRect(0,0,960,470)}}
function prepareCage(im){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height);for(let p=0;p<d.data.length;p+=4)if(d.data[p]>110&&d.data[p+2]>110&&d.data[p+1]<110&&d.data[p]>d.data[p+1]*1.6&&d.data[p+2]>d.data[p+1]*1.6)d.data[p+3]=0;g.putImageData(d,0,0);exitArt.cageCutout=c;
 const door=document.createElement('canvas');door.width=c.width;door.height=c.height;const q=door.getContext('2d');q.drawImage(c,0,0);q.globalCompositeOperation='destination-in';q.beginPath();q.rect(c.width*.105,c.height*.172,c.width*.648,c.height*.663);q.rect(c.width*.032,c.height*.45,c.width*.11,c.height*.15);q.fill();exitArt.cageDoor=door;
 const frame=document.createElement('canvas');frame.width=c.width;frame.height=c.height;const f=frame.getContext('2d');f.drawImage(c,0,0);f.globalCompositeOperation='destination-out';f.drawImage(door,0,0);exitArt.cageFrame=frame;}
function drawDeanCage(open=0,occupied=true){const x=737,y=89,w=205,h=280;ctx.save();ctx.fillStyle='#080d1155';ctx.beginPath();ctx.ellipse(x+w*.5,y+h-9,92,13,0,0,Math.PI*2);ctx.fill();if(occupied)drawDeanFrame(4,820,325,181,1);ctx.drawImage(exitArt.cageFrame,x,y,w,h);ctx.save();ctx.translate(x+w*.754,y);ctx.transform(Math.max(.08,1-open*.92),-open*.16,0,1,0,0);ctx.drawImage(exitArt.cageDoor,-w*.754,0,w,h);ctx.restore();ctx.restore()}
loadExitArt();


