const assert=require('node:assert/strict'),{CombatLab}=require('./combat-engine.js');
let l=new CombatLab();assert(l.god);assert.equal(l.enemies.length,1);
function clear(){for(const e of l.enemies){e.hp=0;l.set(e,'defeated')}l.update(2.3)}
clear();assert.equal(l.wave,2);assert.equal(l.enemies.length,2);assert(l.enemies.some(e=>e.x<135)&&l.enemies.some(e=>e.x>825));clear();assert.equal(l.wave,3);assert.equal(l.enemies.length,3);for(let i=0;i<8;i++)clear();assert.equal(l.wave,11);assert.equal(l.enemies.length,3);assert(!l.over);
l.enemyMode='follow';l.update(12);assert(l.enemies.every(e=>e.x>=135&&e.x<=825));assert.equal(l.player.hp,100);
l=new CombatLab();l.wave=3;l.spawnWave();l.enemyMode='target';l.vinyl=[];for(let i=0;i<3;i++){let e=l.enemies[i];e.entering=false;e.x=l.player.x+60+i*20;e.y=l.player.y;e.hp=100}l.charge=l.settings.recordsNeeded;l.trigger('special');l.update(.65);assert(l.enemies.every(e=>e.hp===60),'special hits all targets once');l.update(.05);assert(l.enemies.every(e=>e.hp===60));assert.equal(l.events.filter(e=>e.type==='shockwave').length,1);assert.equal(l.events.filter(e=>e.type==='hit').length,3);assert(l.events.filter(e=>e.type==='hit').every(e=>e.weapon==='special'));
l=new CombatLab();l.enemyMode='target';l.vinyl=[];l.enemy.x=l.player.x+100;l.trigger('punch');l.update(.3);assert.equal(l.enemy.hp,91);assert.equal(l.events.filter(e=>e.type==='swing').length,1);assert.equal(l.events.filter(e=>e.type==='hit').length,1);assert.equal(l.events.filter(e=>e.type==='action').length,1);
l=new CombatLab();l.enemyMode='target';l.vinyl=[];l.trigger('punch');l.update(.4);assert.equal(l.events.filter(e=>e.type==='hit').length,0,'miss has no impact audio');assert.equal(l.events.filter(e=>e.type==='swing').length,1);
l=new CombatLab();l.enemyMode='target';l.vinyl=[];l.update(.8,{dx:1});assert(l.events.filter(e=>e.type==='step'&&e.who==='player').length>=2);l.events=[];l.update(1);assert.equal(l.events.filter(e=>e.type==='step').length,0);l.trigger('jump');l.update(.8);assert.equal(l.events.filter(e=>e.type==='land').length,1);
l=new CombatLab();l.god=false;l.player.hp=1;l.enemy.x=l.player.x+100;l.enemy.cooldown=0;l.nextAttack=0;l.update(1);assert(l.over);assert.equal(l.player.hp,0);l.update(4);assert.equal(l.wave,1);l.reset();assert.equal(l.player.hp,100);assert.equal(l.wave,1);
l=new CombatLab();l.update(30);assert.equal(l.player.hp,100);assert(l.hits.enemy>0,'infinite health retains reactions');
console.log('PASS: endless 1/2/3 waves, entry from both sides, ten transitions, multi-target shockwave, one-hit-per-target, swing vs impact events, footsteps, jump landing, default infinite health and optional defeat/reset.');
