const assert=require('assert/strict'),fs=require('fs'),{CombatLab}=require('./combat-engine');
function lab(){const l=new CombatLab();l.selectCharacter('em');l.enemyMode='target';l.vinyl=[];return l}
{const l=lab();l.reset();assert.equal(l.player.fighter,'em');assert.equal(l.selectCharacter('bad'),false);l.selectCharacter('promis');assert.equal(l.player.fighter,'promis')}
{const l=lab();l.trigger('kick');assert.equal(l.player.kickVariant,0);assert.equal(l.moveData(l.player).damage,13);l.trigger('kick');l.update(.49);assert.equal(l.player.kickVariant,1);assert.equal(l.moveData(l.player).damage,19);l.update(.7);assert.equal(l.player.action,'idle')}
for(const face of [-1,1]){const l=lab();l.player.x=480;l.player.face=face;l.enemies=[80,270,-90].map((dx,i)=>{const e=l.make('enemy',480+dx*face,-face);e.uid='e'+i;return e});assert.equal(l.trigger('special'),false);l.charge=3;assert(l.trigger('special'));assert.equal(l.charge,0);l.update(.44);assert.equal(l.enemies[1].hp,100);l.update(.48);assert.equal(l.enemies[0].hp,58);assert.equal(l.enemies[1].hp,58);assert.equal(l.enemies[2].hp,100);assert.equal(l.enemies[0].action,'down')}
{const l=lab();l.trigger('jump');l.update(.15);assert.equal(l.player.action,'jump');l.trigger('kick');assert.equal(l.player.action,'kick');l.update(.6);assert.equal(l.player.flight,null);l.trigger('elbow');assert.equal(l.moveData(l.player).damage,20)}
const manifest=JSON.parse(fs.readFileSync('outputs/promis-lab/audio/manifest.json'));assert.equal(manifest.music.source,'Steel_Grate_Ambush.mp3');assert.deepEqual(fs.readFileSync('outputs/promis-lab/audio/'+manifest.music.file),fs.readFileSync('C:/Users/binar/Downloads/Steel_Grate_Ambush.mp3'));
const html=fs.readFileSync('outputs/promis-lab/Promis.html','utf8');new Function(html.split('<script>')[1].split('</script>')[0]);assert(!html.includes('EM_ATLAS_DATA'));assert(html.includes('id="fighter"'));
console.log('PASS DJ Em selection/reset, queued kick combo, directional travelling special both facings, vinyl gating, neutral jump/aerial kick, rising knee, exact replacement music and built script syntax');
