const fs=require('fs');let s=fs.readFileSync('work/intro-runtime.js','utf8');
const a=s.indexOf('function drawCar('),b=s.indexOf('function doorway(',a);
s=s.slice(0,a)+`function drawCar(frame,x,y,w,t){const c=carFrames[frame];if(!c)return;const h=w*c.height/c.width,left=x-w/2,top=y-h;ctx.drawImage(c,left,top,w,h);if(frame<4)return;
const windows=frame===4?{front:[[.342,.414],[.443,.147],[.618,.147],[.618,.413]],rear:[[.657,.151],[.791,.151],[.894,.402],[.657,.414]]}:{front:[[.437,.15],[.615,.15],[.615,.424],[.417,.424]],rear:[[.657,.15],[.79,.15],[.891,.405],[.655,.413]]};
for(const name of ['front','rear']){ctx.save();ctx.beginPath();windows[name].forEach(([px,py],i)=>i?ctx.lineTo(left+px*w,top+py*h):ctx.moveTo(left+px*w,top+py*h));ctx.closePath();ctx.clip();ctx.fillStyle='#14202bcc';ctx.fillRect(left,top,w,h);
for(const seat of cabinSeats(opening.fighter).filter(s=>s.window===name)){if(seat.exit&&t>=4.05)continue;const portrait=seatedPortraits[seat.fighter];if(!portrait)continue;const ph=h*seat.height,pw=ph*portrait.width/portrait.height;ctx.save();ctx.filter=seat.far?'brightness(.60) saturate(.72)':'brightness(.84) saturate(.86)';ctx.drawImage(portrait,left+w*seat.x-pw/2,top+h*seat.y,pw,ph);ctx.restore()}
ctx.fillStyle='#587e8918';ctx.fillRect(left,top,w,h);ctx.restore()}}
`+s.slice(b);
const start=s.indexOf('doorway(t);if(t>=4.05)'),end=s.indexOf('\nif(t>=8.15)',start);
s=s.slice(0,start)+`doorway(t);if(t>=4.05){const p=exitPose(t);ctx.save();ctx.fillStyle='#0a111740';ctx.beginPath();ctx.ellipse(p.x,p.y+1,30,6,0,0,Math.PI*2);ctx.fill();ctx.restore();introHero(opening.fighter,p.pose,p.x,p.y,p.scale,p.face,p.rotation||0,t);if(p.y<365)drawCar(frame,carX,carY,480,t)}
`+s.slice(end);
s=s.replace("t>5.65&&t<6.45","t>5.45&&t<5.95").replace("arcadeText('READY!',555,155","arcadeText('READY!',565,230").replace('arcadeText("LET\'S GO!",555,135','arcadeText("LET\'S GO!",565,218');
s=s.replace('const exterior=new Image(),cars=new Image();','const exterior=new Image(),cars=new Image(),portraits=new Image();').replace('if(++n===2)','if(++n===3)');
s=s.replace("exterior.onerror=cars.onerror=",`portraits.onload=()=>{const sheet=document.createElement('canvas');sheet.width=portraits.width;sheet.height=portraits.height;const g=sheet.getContext('2d');g.drawImage(portraits,0,0);const d=g.getImageData(0,0,sheet.width,sheet.height).data;['promis','change','em','bully'].forEach((f,i)=>{const x0=Math.floor(i%2*sheet.width/2),x1=Math.floor((i%2+1)*sheet.width/2),y0=Math.floor(Math.floor(i/2)*sheet.height/2),y1=Math.floor((Math.floor(i/2)+1)*sheet.height/2);let l=x1,r=x0,top=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*sheet.width+x)*4+3]>150){l=Math.min(l,x);r=Math.max(r,x);top=Math.min(top,y);b=Math.max(b,y)}const c=document.createElement('canvas');c.width=r-l+1;c.height=b-top+1;c.getContext('2d').drawImage(sheet,l,top,c.width,c.height,0,0,c.width,c.height);seatedPortraits[f]=c});done()};portraits.src='data:image/png;base64,SEATED_DATA';exterior.onerror=cars.onerror=portraits.onerror=`);
fs.writeFileSync('work/intro-runtime.js',s);
s=fs.readFileSync('work/combat-runtime.js','utf8').replace('let opening=null','const seatedPortraits={};\nlet opening=null');fs.writeFileSync('work/combat-runtime.js',s);
s=fs.readFileSync('work/build-combat.cjs','utf8').replace("fs.readFileSync('work/opening-sequence.js'","fs.readFileSync('work/cabin-layout.js','utf8')+'\\n'+fs.readFileSync('work/opening-sequence.js'").replace("[['EXTERIOR_DATA'","[['SEATED_DATA','seated-portraits.png'],['EXTERIOR_DATA'");fs.writeFileSync('work/build-combat.cjs',s);
